### ISSUE TITLE
CreateMissingData() fails when more than one domaine is defined

### ISSUE THREAD

**Issue by GeoffreyHuck** [France-ioi/AlgoreaBackend#1001]
`CreateMissingData()` is used to create all mandatory rows in the database (groups, groups_groups, ...) that are required given the configuration.

It fails when more than one domain is specified because it sets `text_id` to `AllUsers` or `TempUsers`. And `text_id` now has a unique constraint: `panic: Error 1062: Duplicate entry 'AllUsers' for key 'groups.text_id'`

**Comment by GeoffreyHuck** [comment]
Before trying to fix this, I need to know if the `text_id` of the groups `AllUsers` or `TempUsers` are used in the frontend? @smadbe

**Comment by smadbe** [comment]
They are not. (groups' `text_id` are not even returned to the frontend)

**Comment by smadbe** [comment]
Fixed in #1010
