### ISSUE TITLE
500 on item deletion

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#1157]
I get a 500 status code on 
```
curl 'https://dev.algorea.org/api/items/5207993233955027100' -X DELETE -H 'Authorization: Bearer ...' 
```
with the usual user.

The error msg is "Error 1217: Cannot delete or update a parent row: a foreign key constraint fails"

Can you check what's happening?

**Comment by zenovich** [comment]
```
curl 'https://dev.algorea.org/api/items/5207993233955027100' -X DELETE -H 'Authorization: Bearer token123' 
{"success":true,"message":"deleted"}
```
🤷

**Comment by zenovich** [comment]
```
curl 'https://dev.algorea.org/api/items/5207993233955027100' -X DELETE -H 'Authorization: Bearer ...' 
{"success":true,"message":"deleted"}
```
🤷

**Comment by zenovich** [comment]
At the same time, we have some foreign keys, restricting items deletion:

fk_items_ancestors_ancestor_item_id_items_id
fk_items_items_parent_item_id_items_id

So, one (or both) of them is the cause.

**Comment by zenovich** [comment]
I suppose a child item might have been added in a concurrent request.

**Comment by zenovich** [comment]
But more likely it was caused by running item ancestors propagation asynchronously after removing children of the item. As a result, the request which removed children completed with a success status leaving items_ancestors undeleted. Then, `itemDelete` was called before the scheduled propagation has been done and failed because it only checks that `items_items` does not contain children, it doesn't check `items_ancestors`.

**Comment by smadbe** [comment]
Yes, I emptied the chapter before deleting it as it is required. 
But so, we should delete in item_ancestors in the delete service as well, right? Why isn't there a cascade deletion on the constraint?

**Comment by zenovich** [comment]
We prohibit deletion of items having children. It’s on purpose

**Comment by smadbe** [comment]
They were deleted, but not propagated yet. But we need a way to prevent this problem, there is no way a user can understand what's happening.
I think the propagation system was broken at the time of the bug, but still, if it may return a 500 during 5min, that's still not ok.

**Comment by smadbe** [comment]
I have another temporary error while the propagation has not been done, on a item children change. From logs:
```
unexpected error: error: conflicting key 'children' rule 'Unknown' with text 'children IDs should be unique and each should be visible to the user' for locale 'en', value being ignored, stack trace: goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/France-ioi/AlgoreaBackend/v2/app/service.AppHandler.ServeHTTP.func1()\n\t/home/circleci/project/app/service/handler.go:34 +0x1ff\npanic({0xc8f500, 0xc0001baf80})\n\t/usr/local/go/src/runtime/panic.go:884...
```
I suppose that's the same cause.

**Comment by zenovich** [comment]
> I have another temporary error while the propagation has not been done, on a item children change. From logs:
> 
> ```
> unexpected error: error: conflicting key 'children' rule 'Unknown' with text 'children IDs should be unique and each should be visible to the user' for locale 'en', value being ignored, stack trace: goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/France-ioi/AlgoreaBackend/v2/app/service.AppHandler.ServeHTTP.func1()\n\t/home/circleci/project/app/service/handler.go:34 +0x1ff\npanic({0xc8f500, 0xc0001baf80})\n\t/usr/local/go/src/runtime/panic.go:884...
> ```
> 
> I suppose that's the same cause.

Yes, I think it has the same cause, but the error is weird. Do you have the full stack trace?

**Comment by zenovich** [comment]
Looks like there was a lock wait timeout as well.

**Comment by zenovich** [comment]
#1162 fixes the issue with the unexpected error.
