### ISSUE TITLE
groups.sPassword cannot be set to NULL

### ISSUE THREAD

**Issue by mblockelet** [France-ioi/AlgoreaBackend#117]
Hi,

The field `groups.sPassword` can be NULL to indicate that a group cannot be joined by password. However, AlgoreaBackend doesn't allow to set this field back to NULL once a password has been set ; the endpoint `/groups/{group_id}/change_password` only allows for a new password to be generated.

Would it be possible to add a way to set this field to NULL? (maybe through the `/groups/{group_id}/change_password` endpoint)

Thanks!

**Comment by zenovich** [comment]
Hi! We can change it to something like `POST /groups/{group_id}/password` (set a newly generated password) and `DELETE /groups/{group_id}/password` (discard the password)

**Comment by mblockelet** [comment]
That sounds like a great idea to me!

**Comment by smadbe** [comment]
I was going to propose something similar. Ok for @zenovich 's proposal.
