### ISSUE TITLE
Handle `lockUserDeletionDate` correctly

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#196]
In a nutshell, `lockUserDeletionDate` is supposed to be used to prevent a user from deleting his account to participate several time to a contest. 
This support should be fully implemented by putting it both in the user deletion (already done) but also to prevent a user to leave these groups. 
Probably this attribute should be renamed to a more appropriate naming (e.g., `user_membership_locked_until`)

**Comment by zenovich** [comment]
This support has been fully implemented two months ago https://github.com/France-ioi/AlgoreaBackend/blame/master/app/api/currentuser/current_user.go#L77

**Comment by zenovich** [comment]
And the column is named 'lock_user_deletion_until' now

**Comment by zenovich** [comment]
So the task is done, I think

**Comment by smadbe** [comment]
Yes, right. My bad.
