### ISSUE TITLE
Merge users_items into groups_attempts

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#286]
Initially only `users_items` were used. Then `groups_attempts` were added to both implement participation in teams and allow several attempts for the same task. 
We now we want to go towards handling a user the same way as a team; and all participations as attempts (even if most items would only allow one attempt at first).

So, we'll merge most of `users_items` data into `groups_attempts`. In practice, we will keep the `users_items` rows (as some of the data is still relevant for now) but the following columns will disappear (they are all in `groups_attempts` already):
```
score
score_computed
score_reeval
score_diff_manual
score_diff_comment
submissions_attempts
tasks_tried
tasks_solved
children_validated
validated
finished
key_obtained
tasks_with_help
hints_requested
hints_cached
corrections_read
precision
autonomy
started_at
validated_at
finished_at
latest_activity_at
thread_started_at
best_answer_at
latest_answer_at
latest_hint_at
contest_started_at
ranked
all_lang_prog
```
(actually but the ids, state/answer and platform_date_removed)

For the data migration:
1. For `users_items` without `active_attempt_id`, they have worked as a single user (no team) and have no `groups_attempt` for themselves on this item.  For these, create a `groups_attempts` with the same data + the group_id being the user's self group + order '1'.
2. For `users_items` with an `active_attempt_id`, typically it is a copy of the data should already be in `groups_attempts` (there are scores not matching but that's ok to loose them); so we can remove the attributes in users_items without doing anything.

The `users_items.platform_date_removed` attribute can be removed as well, it has not been used yet, and we'll find a more appropriate solution later.

The `ancestors_computation_state` used for propagation of the scores does not make sense anymore.

Finally, the "state" and "answer" attribute are just a duplicate from what is in `users_anwers` and can be deleted as well.

**Comment by smadbe** [comment]
Still to do for me: evaluate the impacts on the existing services

**Comment by smadbe** [comment]
Impact on existing services:
- delete user / user dump: trivial changes
- `itemView`: state and answer can be removed as it should be a dedicated call to get them  + "user" subtree should be replaced by "user_active_attempt" with the existing attributes (but state/answer) inside, but active_attempt_id -> attempt_id
- `itemGetAnswerToken`, `itemGetHintToken`: remove `users_items` update, only keep groups_attempts (so can be simplified a bit without the need for a get and the map)
- itemAnswerUpdateCurrent, saveGrade: remove update of `users_items`
- itemTaskTokenGet: remove update of `started_at` and `latest_activity_at` on `users_items`
- updateActiveAttempt: remove update of `latest_activity_at` and `ancestors_computation_state` on `users_items`
- closeContest and closeTeamContest fct: if not contest stop (expired membership) not done yet, just replace the update of `finished_at` on `users_items` by the one on `groups_attempts`.
- ComputeAllUserItems: transform the propagation of scores through `users_items` by propagation through `groups_attempts` (may require creating them if not existing).  `PropagateAttempts` should disappear then.
- getRawNavigationData and getActiveContestInfoForUser: instead of the users_items data, get the same info from the active groups_attempts for the user   
- GetAttemptItemIDIfUserHasAccess fct: remove use of `users_items` which was useless anyway (?)

**Comment by zenovich** [comment]
> ComputeAllUserItems: transform the propagation of scores through users_items by propagation through groups_attempts (may require creating them if not existing). PropagateAttempts should disappear then.

The problem here is that the `groups_attempts` table is not designed for storing aggregated data since it can have (and has) more than one row for same group_id-item_id pair. If we start storing aggregated data into this table as well, it could become a real mess (the 'example' DB already contains 700K of non-aggregated data in `groups_attempts and there will be much more). Probably it would be much better to rename `users_items` into `groups_attempts_aggregated` keeping all the columns (but replacing its `user_id` column with `group_id`) and copy teams attempts data from `groups_attempts` into this table. Although we still would need to save attempts into two tables every time (as we save them currently into `groups_attempts` and `users_items`), the main goal of unifying attempts of teams and single users would be achieved.

**Comment by zenovich** [comment]
> > ComputeAllUserItems: transform the propagation of scores through users_items by propagation through groups_attempts (may require creating them if not existing). PropagateAttempts should disappear then.
> 
> The problem here is that the `groups_attempts` table is not designed for storing aggregated data since it can have (and has) more than one row for same group_id-item_id pair. If we start storing aggregated data into this table as well, it could become a real mess (the 'example' DB already contains 700K of non-aggregated data in `groups_attempts` and there will be much more). Probably it would be much better to create a new table (say`groups_attempts_aggregated`) with the same columns as in `groups_attempts and copy aggregated teams/users attempts data from `groups_attempts`into this table. Although we still would need to update two tables every time (as we do currently with`groups_attempts`and`users_items`), the main goal of unifying attempts of teams and single users would be achieved.

Probably we don't have to create a new table or add new columns into `groups_attempts`. The current `groups_attempts` should be enough for doing the task.

**Comment by zenovich** [comment]
> closeContest and closeTeamContest fct: if not contest stop (expired membership) not done yet, just replace the update of finished_at on users_items by the one on groups_attempts.

Do we still need these two functions?
