### ISSUE TITLE
New item permissions

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#298]
Implement new permission rules and propagation described in https://france-ioi.github.io/algorea-devdoc/design/access-rights/items/

Various remarks:
* There are no more "*_from" date for permissions. For the existing data, they are all with date in the past, so they should just be converted to their value. The date can be used for setting the `latest_update_on`.
* Map gray, partial, full, solution access to respectively info, content, content_with_descendants and solution for "can_view".
* owner access on items become "is_owner"
* manager access in items become can_view=solution, can_grant_view=solution, can_watch=answer, can_edit=all, is_owner=false
* sAccessReason can be lost
* idUserCreated become owner_group_id (through their self_group_id)
* For existing data, set `content_view_propagation` to the partial propagation, `view_propagation_limit` to `solution`, grant_view_propagation to true, watch_propagation to true, edit_propagation to true
* `groupItemEdit` needs major updates. In addition to implement the major rules, it also have to take a new  "group_id"  input :  group as which the user is doing the change.
* create a group named "Former Task Owner" with all task owners in it, and give this group "can_edit" = "children" to all items having `items.bCustomChapter = true`
* [NEW] remove all propagation from the current custom chapters to their direct children
* `items.bCustomChapter` can be removed

**Comment by zenovich** [comment]
> Map gray, partial, full, solution access to respectively info, content, content_with_descendants and solution for "can_view".

We don't have `gray` access in groups_items. We have `cached_grayed_access_since` but it is a generated value.

**Comment by smadbe** [comment]
As answered somewhere else, there is no need to map previous data, but from now, there will be this (equivalent of) gray access that can be given.

**Comment by smadbe** [comment]
Is there anything remaining from this issue which is not in another one?

**Comment by zenovich** [comment]
No. Everything else is in other issues.
