### ISSUE TITLE
Follow the "Error Strings" rule of Go CodeReviewComments

### ISSUE THREAD

**Issue by zenovich** [France-ioi/AlgoreaBackend#30]
Everywhere in the code we have error messages starting with capital letters. At the same time, the “Go Code Review Comments” article recommends start them with lowercase letters (https://github.com/golang/go/wiki/CodeReviewComments#error-strings).

To keep HTTP errors starting from uppercase letters we should modify  code
```
    return &ErrorResponse{
        Response:  response,
        ErrorText: e.Error.Error(), // FIXME: should be disabled in prod
    }
```
in service.httpResponse() to uppercase the first letter. After doing this we can follow the rule without modifying tests.

**Comment by zenovich** [comment]
implemented in #37

**Comment by smadbe** [comment]
You could write "fix #issuenum" in your PR description so that it auto-closes the issue when merged

**Comment by zenovich** [comment]
> You could write "fix #issuenum" in your PR description so that it auto-closes the issue when merged

👍  Will try it next time
