### ISSUE TITLE
Move contest start to attempts

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#300]
* Move `contest_participations .entered_at` to the attempts table (as `contest_entered_at`) as it is related to attempt and not to the group in general.
* Delete the `contest_participations` table as it is empty now
* Update the services

**Comment by zenovich** [comment]
1. In contest_participations we also have 'finished_at' column. Should we create a new column in `groups_attempts` to store values of `contest_participations.finished_at` or use the existing column `groups_attempts.finished_at` for that?
2. In contestSetAdditionalTime service we set `groups_groups.expires_at` of affected `items.contest_participants_group_id` members to `contest_participations.entered_at` + `items.duration` + total additional time.' After moving `contest_participations.entered_at` into groups_attempts, it will be possible to have several different `entered_at` values for the same group_id-item_id pair. Which of them should we use? The same question is for getActiveContestInfoForUser.
3. In contestGetQualificationState, should we ignore finished participations?

**Comment by smadbe** [comment]
1. There should not be any `finished_at` (cfr #296 )
2. Good remark. It should not be possible to enter multiple attempts at the same time for a participant, so pick one knowing it should not happen (you may log if it happens and you can check this without extra cost in Go)
3. Yes
