### ISSUE TITLE
Handle ‘permissions_granted.giver_group_id’ 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#313]
Multiple changes/fix to be done to adapt to the latest decisions about this former `permissions_granted.giver_group_id`: ([doc](https://france-ioi.github.io/algorea-devdoc/design/access-rights/items/) updated)

* We keep this attribute, it represents through which group membership this group has received the permission. (a group (its managers) can give a permission to a single user if they want to)
* Rename `giver_group_id` to `source_group_id` (other suggestion are welcome)
* Add an `origin` attribute which defines what is the origin "process" of this perm.
  - add it to the PK
  - this is an enum:
     * group_membership: when the `group_id` is matching a non-user
     * item_unlocking: you can now easily find all perms which are probably from unlocks 
     * self: when the user set himself as owner of an item he has created (all cases where group_id=giver_group_id in former data)
     * other (to store the former way to get perms (perm given directly to the user in early days of the platform, perm given to the root items, admins), may be fixed later)
     * ...more will be added
* Set as `source_group_id` the `group_id` itself when not matching an existing group (or when 0, or -1)
* ~~To ensure this permission has been given to a group which can receive permission from this source_group_id (and ensure cascading delete if not anymore), `(source_group_id,group_id)` must refer (FK) to `groups_groups.(parent_group_id, child_group_id)` (i.e. group managers can give a permission to the whole group and a descendant of this group).~~
* ~~As a consequence, constraint `fk_permissions_granted_group_id_groups_id` on `group_id` to `groups.id` is not required anymore.~~
* Add a FK on source_group_id to `group`
* Fix `savePermissionsIntoDB`, unlocking and item creation which are not setting the right as `giver_group_id`

**Comment by zenovich** [comment]
> Add a PK on source_group_id to group

FK?

**Comment by zenovich** [comment]
> group_membership: when the source_group_id is matching a non-user

I don't get why it is called 'group_membership'. Also, it is impossible in AlgoreaPlatform since the `source_group_id` is called `idUserCreated` there and it is always either a user's id or 0.

**Comment by zenovich** [comment]
> item_unlocking: you can now easily find all perms which are probably from unlocks

Is there a technique to do that "easily"? I can't find it :(

**Comment by smadbe** [comment]
> > Add a PK on source_group_id to group
> 
> FK?

Fixed


> > group_membership: when the source_group_id is matching a non-user
> 
> I don't get why it is called 'group_membership'. 

Because the origin of this perm is the membership of the group and should be removed if the membership is lost. (saying "group" is not enough as there may be permissions related with management later). 

> Also, it is impossible in AlgoreaPlatform since the `source_group_id` is called `idUserCreated` there and it is always either a user's id or 0.

I meant the `group_id` 

> > item_unlocking: you can now easily find all perms which are probably from unlocks
> 
> Is there a technique to do that "easily"? I can't find it :(

If you take `item_unlocking_rules` joined with the attempts with a.score>iur.score, you have the items which should have been unlocked, if you join that with permission having the default (0?) idUserCreated, we can consider it is the unlock ones.  Is there some wrong in this ?

**Comment by zenovich** [comment]
> Add a FK on source_group_id to group

Do we want to delete all the permissions when deleting their giver's group? (on deleting an account which used to be a manager, for instance)

**Comment by smadbe** [comment]
Yes.
