### ISSUE TITLE
Add an index for hierarchy checking in 'items_items' table

### ISSUE THREAD

**Issue by zenovich** [France-ioi/AlgoreaBackend#33]
In order to do hierarchy checkings for items fast we need to add an index in 'items_items' table on (idItemParent, idItemChild) or on (idItemParent, idItemChild, iChildOrder)

**Comment by smadbe** [comment]
We first have to agree on how we will deal with DB migration on the production DB. It will depend a bit on the deployment workflow still be defined.

**Comment by smadbe** [comment]
@zenovich , the related branch has been merged, is it done?

**Comment by zenovich** [comment]
@smadbe, no, there weren't any migrations in #31.

**Comment by smadbe** [comment]
As you have already added other indexes on other tables, we can continue adding indexes (backward-compatible changes on the db are ok).

**Comment by zenovich** [comment]
That's weird, but the `items_items` table already had had this index when the task was created: ```
  KEY `parentChild` (`idItemParent`,`idItemChild`),
```
Looks like we can just close the task.
