### ISSUE TITLE
Group permissions, step 6: Approvals (partial support) 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#334]
The end goal will be to implement the group permissions as described in https://france-ioi.github.io/algorea-devdoc/design/access-rights/groups/

Step 6: Approvals (partial support)
Description: Add everything in the DB to handle approvals. Do not change existing services so far.

Subtasks:
* add to `groups`:
  - require_personal_info_access_approval: enum(none, view, edit) (default: none)
  - require_lock_membership_approval_until (datetime) (default: null)
  - require_watch_approval (bool, default: null)
* add to `groups_groups`:
  - personal_info_access_approved_at (datetime) + personal_info_access_approved (computed `personal_info_access_approved_at IS NOT NULL`)
  - lock_membership_approved_at (datetime) + lock_membership_approved (computed)
  - watch_approved_at (datetime) + watch_approved (computed)
* add to `group_pending_requests`: (for"join requests)
  - personal_info_access_approved_at
  - lock_membership_approved_at
  - watch_approved_at
* add to `groups_managers`
  - can_edit_personal_info (bool, default: false)

**Comment by zenovich** [comment]
> require_watch_approval (bool, default: null)

Probably it should be 'require_watch_approval (bool, default 0)' (for consistency's sake)

**Comment by zenovich** [comment]
Shouldn't we remove groups.lock_user_deletion_until after adding groups.require_personal_info_access_approval?
