### ISSUE TITLE
Groups: require "can_manage:membership" for member actions

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#335]
Require for the following services, the manager to have "can_manage:membership" level:
- invite members
- ~withdraw invitations~
- accept join requests
- refuse join request
- add subgroup to group (and "can_manager:memberships_and_group" on the child group)
- remove subgroup from group (no condition on the child group)
- list current requests/invitations
- remove member

**Comment by zenovich** [comment]
There is no service for invitations withdrawal :/

**Comment by smadbe** [comment]
😁
Ok, updated

**Comment by zenovich** [comment]
Should a user have any specific permissions (besides being a manager) on a child group in order to be able to add it as a subgroup or remove it from a parent group?

**Comment by smadbe** [comment]
Yes, sorry, I forgot to mention this aspect but it is the moment to change that as well. I still have to rediscuss it with Mathias as I do not find our final decision but consider for now that you need "can_manager:memberships_and_group" on the subgroup to add it. To remove it, you do not need any permission on the child group.

**Comment by zenovich** [comment]
Should this task affect groupRemoveMembers somehow?

**Comment by zenovich** [comment]
For 'list current requests/invitations', the invitations are viewed by a user, not by a group admin.

**Comment by smadbe** [comment]
> Should this task affect groupRemoveMembers somehow?
Yes, missing one.

> For 'list current requests/invitations', the invitations are viewed by a user, not by a group manager.
There is no service to list invitation/requests in a group? `groupRequestsView`!

**Comment by zenovich** [comment]
> There is no service to list invitation/requests in a group? groupRequestsView!

Ah, yes. Sorry.
