### ISSUE TITLE
Services for leave requests

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#345]
* Allow the member of group to create a leave request if `require_lock_membership_approval_until` > now and membership has `lock_membership_approved`.

* Service to withdraw one's leave request 

* Service to accept a leave request (by a manager with can_manage>=membership on the group or one of his ancestor)
* Service to refuse a leave request (by a manager with can_manage>=membership on the group or one of his ancestor)

**Comment by zenovich** [comment]
> Allow the member of group to create a leave request if require_lock_membership_approval_until > now and membership has lock_membership_approved.

What should we do if there is a pending leave request already?

**Comment by smadbe** [comment]
It should be the same policy as we do for invitations and join requests. Success with "unchanged"
