### ISSUE TITLE
Include scores in attempt propagation

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#348]
* Add a new attribute `items_items.weight` INT NOT NULL DEFAULT '1' COMMENT 'Weight of this child in his parent's score computation'.
* In attempt propagation, propagate scores to parents by computing the weighted average among all its children.
* Instead of unlocking by collecting first the items and then unlocking them "id IN (...)", do the unlock directly after each score update request for all processed attempts
* Don't do anything related to unlocking in saveGrade anymore
* Remove `has_unlocked_items` from saveGrade service output

**Comment by zenovich** [comment]
> Add a new attribute items_items.weight INT NOT NULL DEFAULT '1' COMMENT 'Weight of this child in his parent's score computation'

Maybe FLOAT would be better here?

**Comment by zenovich** [comment]
Shouldn't we allow setting/changing the `weight` value somewhere?

**Comment by smadbe** [comment]
> Maybe FLOAT would be better here?

Actually, they have already implemented it in the current db due to a recent customer request, and they did as a int, so let's keep it int and we may change later. 


> Shouldn't we allow setting/changing the `weight` value somewhere?

Yes it should but it is not that important that is available to the user immediately. As they are other changes to be done to these services, we'll change them later.
