### ISSUE TITLE
Fix result (attempt) propagation for non-existing attempts

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#400]
### Goal
The results obtained on a task by a user should be propagated to every parents of this task, even it has not been explored yet (so if there are no attempt yet)

### Remark
In the next step, this will be improved by not creating the attempts for non-visible items. As it will be quite complex for the overall handling and just an "add-on" to the above propagation, it is good to complete this non-trivial task first.

### Subtasks
In attempt result propagation:
  - convert the big update to an INSERT-ON-DUPLICATE-KEY-UPDATE which creates/updates rows for every parent of attempt marked as `to_be_recomputed` which do not have a descendant marked as "to_be_recomputed". 
  - It means we can get rid of the `markAsProcessing` query and probably of the need for the "processing" state.
  - it means we should be able the write the loop as a single query with a CTE (INSERT... WITH.. SELECT..) (?)

**Comment by zenovich** [comment]
> convert the big update to an INSERT-ON-DUPLICATE-KEY-UPDATE which creates/updates rows for every parent of attempt marked as to_be_recomputed which do not have a descendant marked as "to_be_recomputed".

Which unique key should we use for this? Currently there is only one (PRIMARY KEY (`id`))

**Comment by smadbe** [comment]
Good point 😁
Before we have the solution to handle correctly multi-attempts at every level (chapters), we could rely on a constraint we should probably have: uniqueness on item,group,order. 
It would also help making sure our migrations haven't added too much crap...

And actually, there are ...
```sql
 select count(*) from attempts a1 join items i on i.id=a1.item_id 
  where exists (select * from attempts a2 where a2.item_id = a1.item_id and a2.group_id = a1.group_id and a1.order=a2.order and a1.id>a2.id) 
  and i.type='Chapter';
+----------+
| count(*) |
+----------+
|    52616 |
+----------+
```
I would actually expect not a single chapter to have multiple attempts (we created them as there were no attempts at all for chapter in the imported db), how is it possible to have so many? (could you check you have the same result on your db?)

I think enforcing this unique constraint on item,group,order can only be good for us as we should not allow multiple attempts for chapter (at migration, on propagation, on attempt creation) and only have new order for task attempts ... and this constraint would spot the bugs  :-)
