### ISSUE TITLE
Better naming for items.has_attempts + return the actual has_attempt

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#402]
Goal: `items.has_attempts` is a quite bad naming has all items can have at least one item, and a item does not have attempts but allow user to create some. + Return the actual has_attempts when fetching item so that the UI knows if it has to create an attempt directly.

Subtasks:
- Rename `has_attempts` to `allow_multiple_attempts`, with comment: "Whether participants can create multiple attempts when working on this item."
- Next to `best_score` and `validated` in getItem and getNavData, add `has_attempts`: whether the current user has at least one attempt for this item.

**Comment by zenovich** [comment]
> Next to best_score and validated in getItem and getNavData, add has_attempts: whether the current user has at least one attempt for this item.

We removed best_score and validated from getItem recently. Do we still need has_attempts there?

**Comment by zenovich** [comment]
Probably we should also modify contestEnter, contestGetGroupByName, contestListMembersAdditionalTime, contestGetQualificationState and contestSetAdditionalTime somehow because they treat item with allows_multiple_attempts (former has_attempts) as team-only contests.

**Comment by smadbe** [comment]
> Probably we should also modify contestEnter, contestGetGroupByName, contestListMembersAdditionalTime, contestGetQualificationState and contestSetAdditionalTime somehow because they treat item with allows_multiple_attempts (former has_attempts) as team-only contests.

For most of the services, the issues have already been created. For those who just need to know if it is a team or user contest, even they are wrong, there is no clean way to know that for now, so it will wait for the clarification of that first.

**Comment by smadbe** [comment]
> > Next to best_score and validated in getItem and getNavData, add has_attempts: whether the current user has at least one attempt for this item.
> 
> We removed best_score and validated from getItem recently. Do we still need has_attempts there?

Actually after discussing it with Michel, we decided it should be given in getItem instead 😕, sorry about it.

**Comment by zenovich** [comment]
> > > Next to best_score and validated in getItem and getNavData, add has_attempts: whether the current user has at least one attempt for this item.
> > 
> > 
> > We removed best_score and validated from getItem recently. Do we still need has_attempts there?
> 
> Actually after discussing it with Michel, we decided it should be given in getItem instead 😕, sorry about it.

This means getItem should know which attempts to count (individual or team), so it needs a parameter like `as_team_id`, right?

**Comment by smadbe** [comment]
> This means getItem should know which attempts to count (individual or team), so it needs a parameter like `as_team_id`, right?

Yes, #408 and #409
