### ISSUE TITLE
Result propagation: create only attempts for visible items

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#404]
## Goal
If we create attempts for every parent of attempt on which we got result, we may end-up with a "HelloWorld" tasks which has been included by thousands of schools in their custom chapters, and so all users which haves attempts in each of these chapters while they will never get access to these contents.

So we are going to propagate to new attempts **only** if the results may appear in a chapter which is already visible by the user (even if he cannot see the item in between for the moment).

## Subtasks
* in result propagation: only create new attempts (update the existing ones in any case) for which there exists a permission (with can_view>none) such as perm.item is an ancestor of attempt.item and perm.group is an ancestor of attempt.group.
* after each new permission creation (from perm services, unlocking, item creation, ... ) with can_view>none, or update from can_view=none to >none: mark 'changed' every existing attempts such as perm.item is an ancestor of attempt.item and perm.group is an ancestor of attempt.group.
* after each new groups_groups (invite accept, join-request accept, direct add, subgroup add, join by code, contest entering with the contest group): mark 'changed' every existing attempts such as groups_groups.child is an ancestor of attempt.group .... and (optionally**) there exists a perm such as perm.group is an ancestor groups_groups.parent, and perm.item is an ancestor of attempt.item and perm.group is an ancestor of attempt.group. 
* after each new items_items: mark 'changed' every existing attempts such as items_items.child is ancestor of attempt.item .. and (optionally**) there exists a perm such as perm.item is an ancestor of items_items.child and perm.group is an ancestor of attempt.group.

(** Optionally because this is not really required as the permission will be rechecked at propagation, but it helps reducing the number of attempt to propagate.)

**Comment by zenovich** [comment]
> after each new groups_groups (invite accept, join-request accept, direct add, subgroup add, join by code, contest entering with the contest group): mark 'changed' every existing attempts such as groups_groups.child is an ancestor of attempt.group .... and (optionally**) there exists a perm such as perm.group is an ancestor groups_groups.parent, and perm.item is an ancestor of attempt.item and perm.group is an ancestor of attempt.group.

This requirement was implemented as
```
after each new groups_groups (invite accept, join-request accept, direct add, subgroup add, join by code, contest entering with the contest group): mark 'changed' every existing attempts such as groups_groups.child is an ancestor of attempt.group and
1) there exists a perm such as perm.group is an ancestor of groups_groups.parent, and perm.item is an ancestor of attempt.item,
and
2) there is no perm such as perm.group is an ancestor of groups_groups.child and perm.item is an ancestor of attempt.item.
```
(discussed on Slack on 27.01.2020)
