### ISSUE TITLE
Add `as_team_id` for some items/attempts services

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#409]
## Goal
When he is in "team mode", the user should only see what his team can see. Some services have to be adapted to do actions as the team in this case.

## Tasks
* Add `as_team_id` optional parameter query param in the following services. If given, 
  - `itemView`: verify visibility as the team and compute the `has_attempts` for the team  
  - `getNavData`: use the team visibility for items, and attempts for the team only (+ "max among all the user's attempts" -> "max among all the participant's attempts)
* In `contestEnter`, replace the url by `POST /contests/:item_id/enter` and use the `as_team_id` query param to distinguish if it is done as the user or a team. 
* In `contestGetQualificationState`, the same (using `GET /contests/{item_id}/qualification-state`)

**Comment by zenovich** [comment]
> In contestEnter, replace the url by POST /contests/:item_id/enter and use the as_team_id query param to distinguish if it is done as the user or a team.

Should we support team-only contests? If so, how should we determine which contest is team-only and which one is not?

**Comment by smadbe** [comment]
Let's not handle user-only, team-only contests for the moment (ignore this for now in these services). We'll fix this later everywhere and properly.
