### ISSUE TITLE
Add missing FK and cleaning ids in groups_* 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#418]
## Changes

* For `groups_ancestors` and `groups_groups`: 
- add FK to `groups`
- remove `id` 

* For `groups_ancestors`, make `is_self` generated stored (add in the comment that it is generated).

* In `groups_contest_items`, add FK to `items` and `groups`

* In `groups_propagate` add FK from `id` to `groups` (except if we do not want it here?)

**Comment by zenovich** [comment]
> For groups_ancestors, make is_self generated stored (add in the comment that it is generated).

Probably generated virtual would be even better, right?
