### ISSUE TITLE
max size on groups

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#437]
## Overview
Add a maximum number of participants on groups.

## Detail
* New attributes:
  - `max_participants` int >=0 nullable "The maximum number of participants (users and teams) in this group (strict limit if \`enforce_max_participants\`)"
  - `enforce_max_participants` bool, default false, "Whether the number of participants is a strict constraint" -- on change to true, CHECK that `max_participants` is not NULL
* If `enforce_max_participants` is set, do not allow adding a new participants (or create request / invitation) if the new number of participants would exceed `max_participants`. The number of participants is computed as the number of non-expired users or teams which are direct children of the group + invitations. Do the check for:
  - invitation creation (not at accepting)
  - join-request creation and acceptation
  - join by code
* Document this "behavior" somewhere clearly (in the code + swagger specs?), they may change in the future.

**Comment by zenovich** [comment]
> If enforce_max_participants is set, do not allow adding a new participants (or create request / invitation) if the new number of participants would exceed max_participants. The number of participants is computed as the number of non-expired users or teams which are direct children of the group + invitations.

This seems to be weird: if we do not count join requests (since we only count memberships and invitations), then creation of a new join request never can raise the number of participants. So we should either count the join requests or skip checking on creating join requests :/

**Comment by smadbe** [comment]
We do not count join requests on creation but when we accept them (as requests are initiated by users and, if there is one seat left, the administrator may want to pick a specific user among several requesters). However, if he group is already full (actual group members + invitations), it is useless to let the users request to join the group. 
What I wrote looks correct to me.

**Comment by zenovich** [comment]
> We do not count join requests on creation but when we accept them (as requests are initiated by users and, if there is one seat left, the administrator may want to pick a specific user among several requesters). However, if he group is already full (actual group members + invitations), it is useless to let the users request to join the group.
> What I wrote looks correct to me.

Okay. So, for batch operations we should create/accept all invitations/requests (if the limit is not exceeded) or none (if the limit is exceeded for at least one invitation/request or the group is already full), right? Otherwise (if we accept only part of the list), the admin would not be able to pick specific users afterwards.

**Comment by smadbe** [comment]
Yes, right.
