### ISSUE TITLE
Batch user creation service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#456]
## Overview 
Group managers may be allowed to create a set of users in batch (for a contest, ...). See [designs](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_01.Dialogs_02.Create-batch-accounts) for the typical UI.

On `POST /user_batches/`

## Input
* group_prefix: required
* custom_prefix : required string matching `/^[a-z0-9-]{2,14}$/`
* subgroups: non-empty list of objects having:
   * group_id: required
   * count: required >0
* postfix_length: non-optional, min:3, max:29, 
* password_length: non-optional, min:6, max:50

## Actions
* create a user batch entry with the authenticated user as creator (should not fail if it is not a duplicate and FK exists)
* call the login module to create sum of subgroups.count accounts (see [1](https://github.com/France-ioi/login-module-client/blob/master/src/PlatformApi/AccountsManager.php#L19) with as param:
  - prefix: "{group_prefix}\_{custom_prefix}\_"
  - amount: the sum of subgroups.count
  - postfix_length:
  - password_length
  - login_fixed: true
  - language": authenticated user's `default_language`
* create the corresponding users in our db
* put the subgroup[0].count first users in subgroup[0].group_id, and so on ..., "auto-approve" all approvals required by each group

## Output

on success: 
```json
data: [
    { 
      "group_id": 567,
      "users": [
         {"user_id":123, "login":"...", "password":"..."},
         ...
      ]
    }, 
    ...
  ]
```

## Validations
* The authenticated user is manager of the group (or its ancestors) of the group_prefix with at least can_manage:memberships.
* The subgroup.group_id are descendant of the input.group_id or is the group_id itself
* the prefix is `allowed`
*  32^postfix_length > 2* sum of subgroups.count  (to prevent being unable to generate new login)
* sum of subgroups.count + sum of existing batches under the same group_prefix is not > `max_users` of the prefix.

**Comment by zenovich** [comment]
> The authenticated user is manager of the group (or its ancestors) of the group_prefix with at least can_manage:memberships.

In other services we require the current user (or one of his ancestor groups) to be a manager of the input group strictly (we do not consider the input group's ancestor groups). Should we really do that here?
