### ISSUE TITLE
Batch user creation: Preliminary changes

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#458]
## Motivations 
Group managers may be allowed to create a set of users in batch (for a contest, ...). See [designs](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_01.Dialogs_02.Create-batch-accounts) for the typical UI.

The created logins were currently prefixed by a prefix related to the user, it will be moved the group which "orders" this creation. `groups_login_prefixes` which stores the used prefixes can be changed. 

## Subtasks

* New table `user_batch_prefixes`: "Authorized login prefixes for user batch creation. A prefix cannot be deleted without deleting batches using it." with: 
   - **[PK]** `group_prefix` varchar(13) "Prefix used in front of all batches"
   - `group_id` **[FK on delete cascade]** - "Group and its subgroups in which managers can create users in batch"
   - `max_users` UNSIGNED MEDIUMINT: "Maximum number of users that can be created under this prefix"
   - `allow_new`, bool, default true, "Whether this prefix can be used for new creations"  

* New table `user_batches` "Batches of users which have been created." with:
   - **[PK]** `group_prefix` **[FK on DELETE RESTRICT]**  varchar(13) "Authorized (first) part of the full login prefix`
   - **[PK]** `custom_prefix` varchar(14) "Custom (second) part of the full login prefix." + CHECK that is matches `/^[a-z0-9-]+` (to make sure we have uniqueness of the full prefix) 
   - `size` UNSIGNED MEDIUMINT "Number of users created in this batch`
   - `creator_id`, nullable, FK to `users.id` ON CASCADE SET NULL
   - `created_at`, time, default now

* From `groups_login_prefixes`, extract from `prefix`: before/after the pre-last underscore for group_prefix/custom_prefix (so for  "nice_school_classA_", the group prefix is "nice_school" and the custom_prefix is "classA")  set `count` to the number of logins prefixed by the full prefix. 

* Deduce from that, the `group_prefix` table, so with one row per `group_prefix`, `max_users` to 1000 and group_id any of the group_id matching the group_prefix.

* Remove `groups_login_prefixes`

* Remove `users.login_module_prefix`

**Comment by zenovich** [comment]
> Deduce from that, the group_prefix table, so with one row per group_prefix, max_users to 1000 and group_id any of the group_id matching the group_prefix.

There are no prefixed groups in the example db :(

**Comment by smadbe** [comment]
> There are no prefixed groups in the example db :(

But apparently now there are plenty, so we need to be able to migrate them.

**Comment by smadbe** [comment]
Extract rule from current data updated
