### ISSUE TITLE
Get all user batches service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#460]
## Overview 
Group managers may be allowed to create a set of users in batch (for a contest, ...). 
And should be able to list the batches of users they have already created ([see the bottom on this designs](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_d.Invitation-modes)).

On `GET /user_batches/by-group/{group_id}/`

## Input
* group_id (in url)

## Output
* A list of the batches whose the group of group_prefix is one the input group's ancestors ~~and which are "allow_new"~~:
  - group_prefix
  - custom_prefix
  - size
  - creator_id

## Validations
* The current user is manager of the ~~input.group~~ prefix group id (or its ancestors) with at least can_manage:memberships.

**Comment by zenovich** [comment]
> whose the group of group_prefix is one the input group's ancestors

**Comment by zenovich** [comment]
> whose the group of group_prefix is one the input group's ancestors

or descendants?

**Comment by zenovich** [comment]
> The authenticated user is manager of the input.group_id (or its ancestors) with at least can_manage:memberships

In other services we require the current user (or one of his ancestor groups) to be a manager of the input group strictly (we do not consider the input group's ancestor groups). Should we really do that here?

**Comment by zenovich** [comment]
Why do we need to filter by user_batch_prefixes.allow_new?

**Comment by zenovich** [comment]
> > whose the group of group_prefix is one the input group's ancestors
> 
> or descendants?

Don't get the idea behind this.

**Comment by smadbe** [comment]
> Why do we need to filter by user_batch_prefixes.allow_new?

You're right, it is a mistake. I fix it...

> > > whose the group of group_prefix is one the input group's ancestors
> > 
> > 
> > or descendants?
> 
> Don't get the idea behind this.

If we have a structure like this
```
   A
  /  \
B   C 
 \  /   \
  E     F
  / \
 G H
```
If the prefix X is given to `C`, it means that batches can create users anywhere under C, so in C, E, F, G, or H. So in this service which lists batches, we list those related to prefix X in groups C, E, F, H or H as well.
So what's written looks correct. This part is not a permission restriction, just a scope restriction.

> > The authenticated user is manager of the input.group_id (or its ancestors) with at least can_manage:memberships
> 
> In other services we require the current user (or one of his ancestor groups) to be a manager of the input group strictly (we do not consider the input group's ancestor groups). Should we really do that differently here?

In which recent services don't we do that? A manager of a group is implicitly a manager of the descendant groups.

**Comment by zenovich** [comment]
> In which recent services don't we do that? A manager of a group is implicitly a manager of the descendant groups.

I'd say we never do that. All our services require the user to be a manager of the group itself (being a manager of the group's ancestor gives nothing)

**Comment by smadbe** [comment]
You did it in  #456 I've just reviewed for instance.

**Comment by zenovich** [comment]
> You did it in #456 I've just reviewed for instance.

Actually I did the opposite there. ```
	err := srv.Store.ActiveGroupAncestors().ManagedByUser(user).
		Joins(`JOIN user_batch_prefixes ON user_batch_prefixes.group_id = groups_ancestors_active.child_group_id AND `+
			`user_batch_prefixes.allow_new AND user_batch_prefixes.group_prefix = ?`, input.GroupPrefix).
		Where("group_managers.can_manage != 'none'").
		Select("user_batch_prefixes.group_id, user_batch_prefixes.max_users").
		Scan(&prefixInfo).Error()
```
ManagedByUser() selects all the user's ancestors that are group managers, then we join those ancestors' child_group_id to the user_batch_prefixes.group_id directly. So we do not consider descendants of the managed groups.

**Comment by zenovich** [comment]
Ah. Sorry. It really works in the way you said.

**Comment by zenovich** [comment]
> If the prefix X is given to C, it means that batches can create users anywhere under C, so in C, E, F, G, or H. So in this service which lists batches, we list those related to prefix X in groups C, E, F, H or H as well.
So what's written looks correct. This part is not a permission restriction, just a scope restriction.

I still don't get where the input `group_id` is in this graph. For me, it looks like we should display batches linked to groups that are descendants of the input `group_id`.

**Comment by smadbe** [comment]
The input group is the group you are viewing at a given time for which you request this list. (not to be mixed with the filter of "permissions to see a prefix")

And so, the rule here is that you see a prefix rooted at C in C, E, F, G or H as there may be users of this prefix spread in these groups. In a root super group that would contain for instance all schools (containing themselves classes, ...), you should not see all existing prefixes of all schools for instance. Of course showing them in ancestors may make sense as well (if you show for what group the prefix is for), but that a UI choice.

**Comment by smadbe** [comment]
Hum the "Validations" part is not what I expected it to be, I forgot the update it after my last discussions with Mathias. 
Changed
Sorry about that.
