### ISSUE TITLE
Delete a user-batch service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#461]
## Overview 
Group managers may be allowed to create a set of users in batch (for a contest, ...). 
And should be able to delete a batch of users they have already created ([see the bottom on this designs](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_d.Invitation-modes)).

On `DELETE /user_batches/{group_prefix}/{custom_prefix}`

## Input
- group_prefix
- custom_prefix

## Actions
* request the login_module to delete the users with "{group_prefix}\_{custom_prefix}\_" as prefix (`/platform_api/accounts_manager/delete` with `prefix` parameter)
* delete all users with "{group_prefix}\_{custom_prefix}\_" as prefix (ignore the membership locks on groups the authenticated user manage (but not others!))
* delete the user batch entry

## Output

Generic output

## Validations
* The authenticated user is manager of the group (or its ancestors) of the group_prefix with at least can_manage:memberships.
* The group lock should probably be checked before calling the login-module

**Comment by zenovich** [comment]
> The group lock should probably be checked before calling the login-module

What do you call the "group lock"? @smadbe

**Comment by smadbe** [comment]
It is on 
> delete all users with "{group_prefix}_{custom_prefix}_" as prefix (ignore the membership locks on groups the authenticated user manage (but not others!))
If some users are locked in groups not managed by the current user, they cannot be removed and so the operation should be aborted. (we'll see later if we need to allow the deletion of a subpart).
Make sure the service spec (swagger) is clear about what is exactly done by the service.
