### ISSUE TITLE
Attempt at chapter level

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#463]
## Motivation
Being able to do create a new attempt at the chapter level, for instance for re-doing completely a contest, using fresh non-started tasks, even if these tasks have been attempted several time in a first attempt.

(topic also covered in the [doc on attempts](https://france-ioi.github.io/algorea-devdoc/items/attempts/))

### Results
**results** tables (former "attempts" table) "Results of participants on a given item and attempt":
- participant_id [PK]
- attempt_id [PK]
- item_id  [PK] 
- everything from the former "attempts" table but "creator_id" and "order"
- PK on `(participant_id, item_id, attempt_id)`
- FK from `(participant_id, attempt_id)` to the new `attempts` table below
- FK from `items_id` to `items`

### Attempts
**attempts** table (new table): "Attempts of participants (team or user) to solve a subtree of items. An attempt may have several answers. Every participant has a default attempt."
- participant_id [PK, FK to `groups`] 
- id [PK] "Identifier of this attempt for this participant, 0 is the default attempt for the participant, the next ones are sequentially assigned."
- creator_id [FK to `users`, on delete set null], nullable, "The user who created this attempt."
- parent_attempt_id, nullable "The attempt from which this one was forked. NULL for the default attempt."
- root_item_id [FK to `items`, on delete set null], nullable, "The item on which the attempt was created." 
- created_at, default now
- +FK `(participant_id, parent_attempt_id)` to `attempts`

### Answers
* Change attempt_id to `(participant_id, attempt_id, item_id)` FK to `results` table

### Migration
* Create a default attempt (`attempt.id`=0) for every user and team. 
* For all (item,group) with a single attempt and for the first attempt of multi-attempt, use "0" as attempt (in `results`)
* For the other attempt in multi-attempt, create (in the 'order' order) new attempts, copying the creator, with the parent_attempt_id=0, root_item_id=item_id
* The `group_id` becomes `participant_id`

## Consequence in existing services

* url `/attempts/{attempt_id}/...` (3 services) has to be changed to `/attempts/{attempt_id}/items/{item_id}/...` and using the authenticated user as participant_id or `as_team_id` if given as query string
* In tokens, implement the attempt id by the concatenation of the 3 ids separated by commas (?)
* In `contestEnter`: always create a new attempt with an id `max+1` (+ a `result` with `started_at=now`) with parent_attempt_id=0 (for the moment)
* In `itemAttemptCreate`: for the moment: if there is no results yet, create a new result (on attempt 0), if there is already one, create a new attempt (id>0) and a new result.
* In `itemAttemptsView`, for the moment, just return all the results (we'll change it later)
* Update other services using `attempts` for checking group, item, ... to using `results`. When they work on `answers`,  they may not need to join with results/attempts but use the item/group directly 
* In `ComputeAllAttempts` 
   - should probably become ComputeAllResults or PropagateResults
   - parent `results` to propagate to should be those with the same "attempt_id" except if we are on the `root_item_id` in which case we propagate to the `parent_attempt_id`.
   - for the "missing attempts" which are created, propagate to every parents which are descendant of the root_item_id, and to all (as now) if null. (+ the perm check as optimization as now)
* When user or team are created, create their default attempt

**Comment by zenovich** [comment]
> +FK (participant_id, parent_attempt_id) to attempts

**Comment by zenovich** [comment]
> +FK (participant_id, parent_attempt_id) to attempts

**Comment by zenovich** [comment]
> +FK (participant_id, parent_attempt_id) to attempts

We decided to skip this FK because it will cause many problems on deletion (MySQL cannot set a single column of a composite foreign key to NULL)

**Comment by zenovich** [comment]
```
In itemAttemptCreate: for the moment: if there is no results yet, create a new result (on attempt 0), if there is already one, create a new attempt (id>0) and a new result.

When user or team are created, create their default attempt
```
It looks like these two requirements together bring an issue for teams: since the default attempts of teams don't have creator_id set (as none of them are created by a user), we end up with attempts created by nobody in itemAttemptCreate.

**Comment by smadbe** [comment]
> > +FK (participant_id, parent_attempt_id) to attempts
> 
> We decided to skip this FK because it will cause many problems on deletion (MySQL cannot set a single column of a composite foreign key to NULL)

For the records:
Also, a FK from `parent_attempt_id` to `attempts.id` has not been created as `attempts.id` is not the `attempts` PK. The PK is `(participant_id, id)`, `id` is more like an order. So an `id` may exist but for another participant, which would make the FK completely useless.
