### ISSUE TITLE
Prevent multiple participation in contest

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#487]
## Motivations

As contests allow multiple attempts and team may be reused in several contests, the check for preventing multiple simultaneous participation has to be updated.

## Tasks

* For entering into a contest (so "enter" and "qualification state" services, alone or in team), instead of the current "checkTeamID", check that there is no existing attempt on this item and with, as participant, the current user or a team the current user if member of. If there are attempts and the item allows multiple attempts, check that no attempts allow submissions.
* Get rid completely of getActiveContestItemIDForUser (not relevant anymore)
* Do not extra-check on "team_item_id" in services: 
   -  getGroupByName
   - getMembersAdditionalTimes
   - createAttempt
   - getTaskToken
   - getAttempts
* In acceptGroupInvitation, joinGroupByCode, sendGroupJoinRequest, acceptJoinRequests, inviteUsersk, remove check related to team_item_id
* in createGroup, remove the `item_id` input
* remove getCurrentUserTeamByItem

**Comment by zenovich** [comment]
Should the contestListMembersAdditionalTime list only users when items.entry_participant_type = 'User', only teams when items.entry_participant_type = 'Team', and only teams and users when  items.entry_participant_type is null? (Currently it lists only teams when items.entry_participant_type = 'Team' and descendants of ANY kind otherwise.)

If we want the service to list only users & teams, then we need some another way for getting additional time for groups of other kinds (since they also can have additional time set).

Also, team_item_id is used to prevent users from joining several teams attending the same contest. If we remove this column, how will we handle this?

**Comment by smadbe** [comment]
First, `entry_participant_type` should not be null for a contest. To be consistent with the other attributes, we should not put it nullable but "User" by default, even if it is irrelevant for non-contests.

So for any timed items, it is always either Team or User, not both.
I think it answers your question.

This service does not provide way to get additional time for a non-team-nor-user.

> Also, team_item_id is used to prevent users from joining several teams attending the same contest. If we remove this column, how will we handle this?

It will be handle when a member is added by any way. Handled in #492

**Comment by zenovich** [comment]
> > Also, team_item_id is used to prevent users from joining several teams attending the same contest. If we remove this column, how will we handle this?
> 
> It will be handle when a member is added by any way. Handled in #492

It looks like #492 doesn't handle the situation where a user joins two different teams (not having any attempts for now), but then both teams enter a same contest.

**Comment by zenovich** [comment]
Also, a user can join one team, participate in some contest, leave the team, join another team and participate in the same contest again.

**Comment by smadbe** [comment]
> It looks like #492 doesn't handle the situation where a user joins two different teams (not having any attempts for now), but then both teams enter a same contest.

It is in this one. "For entering into a contest (so "enter" and "qualification state" services, alone or in team), instead of the current "checkTeamID", check that there is no existing attempt on this item and with, as participant, the current user or a team the current user if member of. If there are attempts and the item allows multiple attempts, check that no attempts allow submissions."

> Also, a user can join one team, participate in some contest, leave the team, join another team and participate in the same contest again.

If a contest admin wants to prevent that, he can freeze the team (#491) :-)
