### ISSUE TITLE
Attempt expiration

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#488]
## Motivations

* In case a participant attempts a contest second time (once his first trial is over), he will get can_view:content on the contest while it is not supposed to be able to modify the first attempt anymore. 
* When a contest is over, we may give view:content access to everybody to read the tasks again and the submitted answers. 

## Tasks

* Add a new attribute "allow_submissions_until" on attempts (new attempts, not results), datetime, default "9999-12-31...", "Time until which the participant can submit an answer on this attempt"
* When entering into a contest, the created attempt computes `allow_submissions_until` the same way the current group membership expiration is computed.
* When the additional time is changed, update the `allow_submissions_until` of the last attempt (greatest allow_submissions_until) unless the new allow_submissions_until value would be < now.
* On submit / get hint (`CheckSubmissionRights` &co functions), ensure the attempt allow submissions.

(the checks to be updated for multiple-attempts on entering are handled in a separate issue)

**Comment by zenovich** [comment]
> When the additional time is changed, update the allow_submissions_until of the last attempt (greatest allow_submissions_until)...

Probably it would be better to determine the last attempt by attempts.id

**Comment by zenovich** [comment]
> When the additional time is changed, update the allow_submissions_until of the last attempt (greatest allow_submissions_until) unless the new allow_submissions_until value would be < now.

This can change the allows_submissions_until value of the default attempt which looks like a problem

**Comment by zenovich** [comment]
> When the additional time is changed, update the allow_submissions_until of the last attempt (greatest allow_submissions_until) unless the new allow_submissions_until value would be < now.

Did you mean 'unless the OLD allows_submission_until value would be < now'? For `groups_groups.expires_at` we check the old value. The logic behind this is that we do not restore expired participations.

**Comment by smadbe** [comment]
> > When the additional time is changed, update the allow_submissions_until of the last attempt (greatest allow_submissions_until)...
> 
> Probably it would be better to determine the latest attempt by attempts.id

It is only valid under the assumption you cannot have several timed attempts at the same time, which is the case currently, so yes you can.

> This can change the allows_submissions_until value of the default attempt which looks like a problem. Probably we should filter on root_item_id, but what the item doesn't require explicit entry?
There is a few words missing in your sentence. Of course, it should be only for items which required explicit entry (those with duration must always be explicit-entry!), so they have no default attempt. But additional time is only for those, so that should be a problem.

> > When the additional time is changed, update the allow_submissions_until of the last attempt (greatest allow_submissions_until) unless the new allow_submissions_until value would be < now.
> 
> Did you mean 'unless the OLD allows_submission_until value would be < now'? For `groups_groups.expires_at` we check the old value. The logic behind this is that we do not restore expired participations.

We want on purpose to restore expired participations. I think the additional time is already re-opening access, so that's the same idea.

**Comment by zenovich** [comment]
> We want on purpose to restore expired participations. I think the additional time is already re-opening access, so that's the same idea.

But actually it never does (we do not update groups_groups.expires_at if the participation has been expired)

**Comment by smadbe** [comment]
Are you sure? 
But anyway, it is a good opportunity to do it then :-)

**Comment by zenovich** [comment]
> Are you sure?
Absolutely (see https://github.com/France-ioi/AlgoreaBackend/blob/master/app/api/contests/set_additional_time.go#L186)

> But anyway, it is a good opportunity to do it then :-)
Okay, I'll try.

**Comment by zenovich** [comment]
> > Are you sure?
> 
> Absolutely (see https://github.com/France-ioi/AlgoreaBackend/blob/master/app/api/contests/set_additional_time.go#L186)
> 
> > But anyway, it is a good opportunity to do it then :-)
> 
> Okay, I'll try.

done
