### ISSUE TITLE
getAnswer: fix permissions

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#505]
## Motivations
Some small changes are required on `itemAnswersView` to match recent global changes.

## Subtasks
* optional parameter `as_team_id` -> and so it should not be "The user should have at least 'content' access to the item." but "The participant should have at least 'content' access to the item."
* manager access: fix can watch on users and items TODO

**Comment by zenovich** [comment]
@smadbe Can we close it? It looks like it has been implemented in #1183, #811
