### ISSUE TITLE
Ensure group_id are not users when given for group operations

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#508]
## Motivations
It seems that at multiple places, the type of the input group are not checked even while the operation are not compatible with "users", for instance for adding children to them. 

## Changes

_I'm not 100% sure here, it is just by quickly reading the code, I may have miss some checks._

### createUserBatch
We do not check that the group_id in subgroups are valid groups to put user in. 
Check that these groups are not of type "User".

### CreateRelationsWithoutChecking function
`CreateRelationsWithoutChecking` function comments should mention that the caller must ensure that the parent groups are not users. 

### getGroup
Should exclude users from dest. They may be returned as "ManagedByUser" is used in the query.

### createGroup
Prevent creation of team, but not users?!

### change code, discard code
Should not be applicable to users

### all request, invite, remove/add members services
Check the the container cannot be a user.

**Comment by zenovich** [comment]
> createGroup
>
> Prevent creation of team, but not users?!

Actually createGroup doesn’t allow to create groups of type 'User', 'Base' or ‘ContestParticipants’.
```
Type string `json:"type" validate:"set,oneof=Class Team Club Friends Other Session"`
```
