### ISSUE TITLE
Proper permissions for setting additional time

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#509]
## Motivations
Services which update additional are still using the initial permissions, adapt them to new ones.

### contestSetAdditionalTime
* the current user should have:
  * `can_grant_view >= enter` on item 
  * `can_watch >= result` on item
  * be manager of the group with `can_grant_group_access` and `can_watch_members`
* remove "the authenticated user should have at least `content_with_descendants` access on the input item"

### contestAdminList
* same as contestSetAdditionalTime
* add to the `Where("items.duration IS NOT NULL")` filter, the check that it is an explicit-entry item

### contestListMembersAdditionalTime
* same as contestSetAdditionalTime
* "having at least 'info' access to the item" -> "who can view (at least 'can_view:info') or enter (can_enter_until - can_enter_from > 0) the item".
* remove "the authenticated user should have solutions or full access on the input item;" 

### contestGetGroupByName
* same as contestSetAdditionalTime
* "the group has access to the contest (info, content or content_with_descendants);" -> "the group can view (at least 'can_view:info') or enter (can_enter_until - can_enter_from > 0) the item"
* remove "the authenticated user should have at least content_with_descendants access on the input item."

**Comment by zenovich** [comment]
Probably we still should check that the item(s) is (are) visible for the current user in contestSetAdditionalTime & contestAdminList, right?

**Comment by zenovich** [comment]
For contestListMembersAdditionalTime & contestGetGroupByName, does `can view (at least 'can_view:info') or enter (can_enter_until - can_enter_from > 0) the item` mean that we want to display invisible (for the given group) groups when the given group is able to enter?

**Comment by zenovich** [comment]
`can_enter_until - can_enter_from > 0` doesn't guarantee that a group can enter the item (e.g. both may be in the past).

**Comment by smadbe** [comment]
(Disclaimer: that's very old stuff, everything may not be very clear for me at first)

> Probably we still should check that the item(s) is (are) visible for the current user in all these services, right?

You are not supposed to be able to have `can_grant_view >= enter` without visibility on the item, so no need to check.

> mean that we want to display invisible (for the given group) groups when the given group is able to enter?

What do you mean? Didn't you mean invisible item?

> `can_enter_until - can_enter_from > 0` doesn't guarantee that a group can enter the item (e.g. both may be in the past).

Here the goal is to change additional time of participants having access to the contest... so if the user had access until 10sec ago but has lost it, we should be able to add him time... so having can_enter_until & can_enter_from in the past seems correct (I may be wrong).

**Comment by zenovich** [comment]
>> mean that we want to display invisible (for the given group) groups when the given group is able to enter?

> What do you mean? Didn't you mean invisible item?

Yes, I meant items invisible for the given group...

**Comment by zenovich** [comment]
>> can_enter_until - can_enter_from > 0 doesn't guarantee that a group can enter the item (e.g. both may be in the past).

> Here the goal is to change additional time of participants having access to the contest... so if the user had access until 10sec ago but has lost it, we should be able to add him time... so having can_enter_until & can_enter_from in the past seems correct (I may be wrong).

I think we should also check that can_enter_from is in the past then.

**Comment by smadbe** [comment]
> > Here the goal is to change additional time of participants having access to the contest... so if the user had access until 10sec ago but has lost it, we should be able to add him time... so having can_enter_until & can_enter_from in the past seems correct (I may be wrong).
> 
> I think we should also check that can_enter_from is in the past then.

Not only for those in the past, it was just an example.

> > > mean that we want to display invisible (for the given group) groups when the given group is able to enter?
> 
> > What do you mean? Didn't you mean invisible item?
> 
> Yes, I meant items invisible for the given group...

So, yes, even the item is not yet visible by the given group.
