### ISSUE TITLE
Group view: add level of management 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#510]
## Motivations
When displaying a group, the frontend needs to know if it has to display some buttons for edition, membership management, ... 

## Subtasks
* add current_user_can_manage ('none', 'memberships', 'memberships_and_group')
* add current_user_can_grant_group_access
* add current_user_can_watch_members

**Comment by zenovich** [comment]
It looks like this task is duplicated by #564

**Comment by smadbe** [comment]
Yes sure.
