### ISSUE TITLE
New service: group code check

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#511]
## Overview 
When a temp user wants to join a group by code, it first has to create a non-temp user for it. 
To prevent creating a user if the group code is wrong,  allow checking a group code without applying it.

On `GET /groups/{group_id}/is-code-valid?code=...`

## Input
* code: required string

## Output
* valid: true|false

## Validations
* none

**Comment by zenovich** [comment]
Probably there should not be `/{group_id}/` in the URL since users don't know the group id when joining by code.

**Comment by zenovich** [comment]
Should we also check if the group membership is frozen or if the entry conditions allow to join the group?

**Comment by smadbe** [comment]
> Probably there should not be `/{group_id}/` in the URL since users don't know the group id when joining by code.

Right. 

> Should we also check if the group membership is frozen 

Yes, good idea.

> or if the entry conditions allow to join the group?

Yes, probably as well.

**Comment by zenovich** [comment]
>> or if the entry conditions allow to join the group?

> Yes, probably as well.

Hm... Since temporary/new users probably don't have ancestors with needed permissions_granted.can_enter_from & permissions_granted.can_enter_until for the item (do they???), it can be hard to check this part correctly...

**Comment by zenovich** [comment]
> > > or if the entry conditions allow to join the group?
> 
> > Yes, probably as well.
> 
> Hm... Since temporary/new users probably don't have ancestors with needed permissions_granted.can_enter_from & permissions_granted.can_enter_until for the item (do they???), it can be hard to check this part correctly...

But probably passing `AllUsersGroupID` instead of the user id into check can work.

**Comment by smadbe** [comment]
If you validate that the user is a temp user, you can use this property, yes. But this service is not supposed to be limited to temp user I think... ok, let me recheck the workflow related with this issue first.

**Comment by smadbe** [comment]
Ok, I dug into my notes to find the full workflow related with this requirement.  I wrote it down there: https://france-ioi.github.io/algorea-devdoc/auth/login-by-group-code/

To come back to this issue, yes the goal is just that a newly-created user can join the group, so what you said is valid.
