### ISSUE TITLE
Rename Root*Group config param

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#520]
## Motivations
RootGroup, RootSelfGroup, RootTempGroup are not clear. 

## Subtasks
* rename "RootGroup" -> AllUsersGroup
* rename "RootSelfGroup" -> NonTempUsersGroup, (or PersistentUsersGroup but it is less clear)
* rename "RootTempGroup" -> TempUsersGroup

(I wonder if we should really keep this RootGroup as it is just the parent group of the 2 others that the domain creator can organize as he wants)

**Comment by zenovich** [comment]
> (I wonder if we should really keep this RootGroup as it is just the parent group of the 2 others that the domain creator can organize as he wants)

Actually RootGroup has only one child (RootSelf) while RootTemp is a child of RootSelf. Kinda weird.

**Comment by smadbe** [comment]
Have you checked in the PHP and/or the anonymized db to see if it was the same?

**Comment by zenovich** [comment]
> Have you checked in the PHP and/or the anonymized db to see if it was the same?

In the anonymized DB there are 25 groups with sType = 'Root' and they have children of different kinds:
```
mysql> select groups.id,groups.sType, sName from groups_groups join `groups` on groups.id=groups_groups.idGroupChild where idGroupParent=10;
+----+-----------+-----------+
| id | sType     | sName     |
+----+-----------+-----------+
|  1 | RootAdmin | RootAdmin |
|  3 | RootSelf  | RootSelf  |
+----+-----------+-----------+
```
But if we consider only the group with sType='Root' and sTextID = 'Root' (id=10), it has only two children ('RootAdmin' and 'RootSelf'):
```
mysql> select groups.id,groups.sType, sName from groups_groups join `groups` on groups.id=groups_groups.idGroupChild where idGroupParent=10;
+----+-----------+-----------+
| id | sType     | sName     |
+----+-----------+-----------+
|  1 | RootAdmin | RootAdmin |
|  3 | RootSelf  | RootSelf  |
+----+-----------+-----------+
```
The RootTemp group is one of the RootSelf's children:
```
mysql> select groups.sTextID, groups.sType from groups_groups join `groups` on groups.id=groups_groups.idGroupChild where idGroupParent=3 and groups.sTextID != '';
+----------+----------+
| sTextID  | sType    |
+----------+----------+
| RootTemp | UserSelf |
+----------+----------+
1 row in set (0.07 sec)
```

**Comment by smadbe** [comment]
Ok, we had something like
```
                Root
              /     \
       RootAdmin  RootSelf
                 /   |  | \
          RootTemp   all users...
```
So:
- RootAdmin should have disappeared (even if I do not actual deletion of the RootAdmin groups)
- Root is quite useless if it has only RootSelf in it. So it could be deleted, after making sure permissions (if any) are given to the "corresponding" RootSelf.
- there is no group with non temp users... ok... but let's say it is maybe not useful for now
- If RootSelf is parent of RootTemp, so it could be named "AllUsers"
- RootTemp could be named "TempUsers" then.

Does it look fine to you?

**Comment by zenovich** [comment]
Yes, it looks fine

**Comment by smadbe** [comment]
Ok, you can go for it then :-)

**Comment by zenovich** [comment]
Should we change `name`, `text_id`, `description` of these groups in the DB accordingly as well?

**Comment by smadbe** [comment]
Yes!
