### ISSUE TITLE
New service: get official sessions

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#521]
## Overview 

List all official sessions related to an as shown on this screen:
![example](https://france-ioi.github.io/algorea-designs/img/03.Activities_01.Content_e.Content%20and%20session%20alt.png)

On `GET /items/{item_id}/official_sessions`

## Input
* item_id in url

## Output
List of groups which match type 'Session', `is_official_session`=t, `is_public`=1, `activity_id`=input.item_id, with:
- group_id
- name
- description
- open_contest
- require_personal_info_access_approval
- require_lock_membership_approval_until
- require_watch_approval
- require_members_to_join_parent
- is_public
- organizer
- address_line1
- address_line2
- address_postcode
- address_city
- address_country
- expected_start
- current_user_is_member
- current_user_is_manager
- parents: list of parent groups with are visible (is public or the current user is manager or member)
  - group_id
  - name
  - is_public
  - current_user_is_member
  - current_user_is_manager

## Validations
* the current user must have can_view>=info on the item

**Comment by zenovich** [comment]
> parents: list of parent groups with are visible (is public or the current user is manager or member)
group_id
name
is_public
current_user_is_member
current_user_is_manager

1. Should we list only parent groups or all ancestor groups?
2. Should we show non-public (and not managed by the user) 'parent groups' that are ancestors (but not parents) of the current user?
3. Does 'current_user_is_member' is about being a direct member or a descendant of the group? (we have a field with the same name in groupGet where it means being a direct member)
4. How do we order these 'parent groups'?

**Comment by zenovich** [comment]
> List of groups which match type 'Session', is_official_session=t, is_public=1, activity_id=input.item_id, with:

Shouldn't we show groups that are managed by the current user / parents or ancestors of the current user as well?

**Comment by zenovich** [comment]
How should we order the official sessions?

**Comment by smadbe** [comment]
>     1. Should we list only parent groups or all ancestor groups?

Only parents.
 
>     2. Should we show non-public (and not managed by the user) 'parent groups' that are ancestors (but not parents) of the current user?

Only parents.
 
>     3. Does 'current_user_is_member' is about being a direct member or a descendant of the group? (we have a field with the same name in groupGet where it means being a direct member)

A user is not an implicit member of the descendant (but a manager is!) so I don't think it is relevant. Actually for current_user_is_manager the question is relevant, and yes, you should consider the user as manager if he is a manager of one of the ancestor.
 
>     4. How do we order these 'parent groups'?

+name, +id.


> > List of groups which match type 'Session', is_official_session=t, is_public=1, activity_id=input.item_id, with:
> 
> Shouldn't we show groups that are managed by the current user / parents or ancestors of the current user as well?

Yes, if a teacher T is part of a "group of teachers" G which is managing a group S, the teacher T is manager of S (and of all descendant of S)

**Comment by smadbe** [comment]
> How should we order the official sessions?

+expected_start, +name

**Comment by zenovich** [comment]
>>> List of groups which match type 'Session', is_official_session=t, is_public=1, activity_id=input.item_id, with:

>> Shouldn't we show groups that are managed by the current user / parents or ancestors of the current user as well?

> Yes, if a teacher T is part of a "group of teachers" G which is managing a group S, the teacher T is manager of S (and of all descendant of S)

But the requirements don't say we should display non-public groups managed by the user. Should we?

**Comment by zenovich** [comment]
>> 2. Should we show non-public (and not managed by the user) 'parent groups' that are ancestors (but not parents) of the current user?

> Only parents.

What about non-public (but managed by the user) parents?

**Comment by zenovich** [comment]
> > How should we order the official sessions?
> 
> +expected_start, +name

`expected_start` can be NULL. Should the NULL values go first?

**Comment by smadbe** [comment]
What makes the most sense for a list of events is to order them by date, so I think using `expect_start` is the best choice for now (may require a filter to remove the past ones, but we can see that later).
We can ignore pagination for now for this service if you want.

**Comment by smadbe** [comment]
> But the requirements don't say we should display non-public groups managed by the user (and nothing about the groups where the user is a member alread). Should we show such groups?

Ah right, this is not really required actually, so you can ignore them (except if it is simpler/cleaner to consider the classical group visibility).
