### ISSUE TITLE
Limit: put an hard limit

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#53]
Do not let the requester set a very huge limit (the limit parameter) as it may affect performance and be a base a DoS attack.  Max the given value with a fixed value (5000?).

**Comment by smadbe** [comment]
@zenovich : completed, right?

**Comment by zenovich** [comment]
@smadbe, not really. We have to employ the `QueryLimiter` in all the services returning objects lists. For now, there are still some services (like `itemAnswerGet`) that don't use it.
