### ISSUE TITLE
Support for cookie-stored token 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#576]
## Motivations

As storing access token in browser local or session storage is considered harmful in terms of security (as any JS code on the domain can access them, leaving some doors open for XSS), we can either:
- store the token in the running app only (subject to steal, auth lost each tab the app is refreshed, closed, ...)
- rely on httonly (non-available to JS) cookies for keeping the token (but cannot be both on different domain (`SameSite=none`) and on http (not `secure`), which makes local dev difficult)

Some ref [here](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#Local_Storage), [here](https://dev.to/rdegges/please-stop-using-local-storage-1i04), [here](https://medium.com/@benjamin.botto/secure-access-token-storage-with-single-page-applications-part-1-9536b0021321)

## Subtasks
* Add a `?use_cookies` (if you prefer to just infer it from other parameter, that's ok as well) in tempUserCreate and accessTokenCreate
  - if given, set the token in a cookie instead of in "data"
  - keep providing `expires_in` in the json response
  - if use_cookies is given, support the input parameters: 
    * `cookie_secure`. If given, add "Secure" attribute to cookie)
    * `cookie_same_site`. If given, add SameSite=Strict attribute to the cookie, otherwise SameSite=None
    * as a cookie cannot be both non-secure and none-same-site, fail if none of the arg if given (with an understandable error message)
  - store the `secure` and `same_site` cookie attribute in the db together with the token
  - infer cookie `domain`and `path` from backend config
  - set the Expires and Max-Age attributes to the cookie
  - always set the `HttpOnly` cookie attribute
* In authLogout, if this token was given as cookie, clear the cookie. 
* In the auth middleware, check for the cookie. If given, use it as a token. If both cookie and Authorization header is given, use the Authorization header.

## Implementation details
There are two ways of providing session token: via the 'Authorization' header and via the 'access_token' cookie.

The middleware we use for the services requiring authentication, prefers the 'Authorization' header when it is given. Also, when both the cookie and the header are given, the cookie gets deleted by the middleware using correct cookie attributes. When only 'access_token' cookie is given, it doesn't become deleted.

The accessTokenCreate service, when called with the 'code' parameter, ignores the 'access_token' cookie, but fails if the 'Authorization' header is given. If the service responds with a new token and an old cookie exists with different attributes (or the new token is returned in JSON), the old cookie gets deleted (otherwise, overwritten).

The tempUserCreate service acts similar way. It ignores the 'access_token' cookie, but fails if the 'Authorization' header is given. If the service responds with a new token and an old cookie exists with different attributes (or the new token is returned in JSON), the old cookie gets deleted (otherwise, overwritten).

The authLogout service works through the authentication middleware (see above) handling the 'Authorization' header and the 'access_token' cookie as any other service requiring the user to be authenticated. Then the service deletes the session cookie (if it is given).

In order to be able to delete session cookies explicitly with correct attributes, we store variable attributes' values inside the session cookie itself, together with the access token. The session cookie is encoded as 'security_kind!token!cookie_domain!cookie_path'. The 'security_kind' is one of 1 (SameSite=Strict), 2 (Secure, SameSite=None), 3 (Secure, SameSite=Strict).

**Comment by smadbe** [comment]
**Problem:**
Frontend and backend must be on the same domain for that. While this is already the case in prod, it complicates development.

**Comment by zenovich** [comment]
RFC6265 states (https://tools.ietf.org/search/rfc6265#section-3.1):

> Finally, to remove a cookie, the server returns a Set-Cookie header with an expiration date in the past. The server will be successful in removing the cookie only if the Path and the Domain attribute in the Set-Cookie header match the values used when the cookie was created.

That means we should know 'cookie_path' and 'cookie_domain' in authLogout in order to remove the cookie. A further investigation showed that we also need to know 'cookie_secure' and 'cookie_same_site'. The cookie is not removed if at least one attribute mismatches.

Btw, why don't we want to store those four cookie attribute values in the config? Actually we already have domains and rootPath in the config, can we use them for cookies?

**Comment by smadbe** [comment]
> Btw, why don't we want to store those four cookie attribute values in the config? Actually we already have domains and rootPath in the config, can we use them for cookies?

Yes, you're right, after these re-re-re-rework of this auth solution taking every parts into account, I lost myself ;-)
`domain` and `path` does not seem to be required as the server may infer it easily with data which is already available (from domain config or Host header, and from rootPath config).
For `secure` and `same_site`, they cannot be inferred with certainty by the server, so they need to be provided by the client... or from a config your are right.  The problem is that we may run the main server on the same domain on https, but run staging, localhost, or alternative (we have a use case where the tasks will be in http, so the SPA in http, so the backend in http) on a domain which is different from the backend... so I don't think that is a good idea to have these in a backend config.

However, to come back to your initial problem, there is no problem of providing `secure` and `same_site` in the logout service. 

I've update the description.

**Comment by zenovich** [comment]
Added the implementation details to the task's description.
