### ISSUE TITLE
Prerequisite service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#612]
## Overview 
Retrieve the prerequisites of an item. ([design](http://dev.algorea.org/branch/design/task/13?refresh=1603469245065))

On `GET /items/:id:/prerequisites`

## Input
* item id

## Output
* list of (visible) items for which the given item is `dependent_item_id`
* include score, grant_content_view
* for each item, include the same attributes as itemChildrenView (but `results`) 

## Validations
* the input item id must be visible can_view>=info
* other items must be visible with can_view>=info

**Comment by zenovich** [comment]
Shouldn't we support the `as_team_id` parameter here?

**Comment by smadbe** [comment]
Yes we should.

**Comment by zenovich** [comment]
Should we support the `watched_group_id` parameter here?

**Comment by smadbe** [comment]
Yes, but then you should not include all participant-related things (score, validated, ...) in this case.

**Comment by smadbe** [comment]
Edit: no `results`
