### ISSUE TITLE
itemUpdate service very slow for updating children

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#623]
On the anonymized prod db, just for updating 2 children of an items (which already exists, so no changes required), the service takes >7sec:
```
curl 'https://dev.algorea.org/api/items/754307144702229123' -X PUT -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5'-H 'Authorization: Bearer ***' -data-raw '{"children":[{"item_id":"426313127344282113","order":0},{"item_id":"178573120557837616","order":1}]}'
```

**Comment by zenovich** [comment]
Which id does the current user have here?

**Comment by smadbe** [comment]
670968966872011405

**Comment by smadbe** [comment]
Updating children 1980584647557587953 (with the same user) takes more than 15sec (timeout on lambda).

**Comment by zenovich** [comment]
> On the anonymized prod db, just for updating 2 children of an items (which already exists, so no changes required), the service takes >7sec

**Comment by smadbe** [comment]
Just don't always remove everything to re-add if that's the flaw. Have you profiled the request? 7 seconds is huge.

**Comment by zenovich** [comment]
Sure, I have profiled the request:
The first INSERT ... ON DUPLICATE KEY UPDATE marking results as 'to_be_recomputed' takes 2s.
Result propagation: 790ms, 2s, 517ms, 618ms, 1s, 1.8s, 70ms (~6s in total)
Permissions insertion takes 333ms.
And the last UPDATE (setting result_propagation_state = 'done') takes 1s.
So, ~10s for the slowest request.

**Comment by zenovich** [comment]
I'm going to rework itemUpdate so that it would not recreate items_items every time.
