### ISSUE TITLE
All breadcrumbs from roots

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#638]
## Overview 
When listing items solved by another user or by yourself, the item name may not be enough to understand what this item is exactly. On "hover", we will display the possible breadcrumbs the user used to access this item.

On `GET /users/{:participant_id|current-user}/items/{ids}/breadcrumbs-from-root` (? ... or anything better)

## Input
* an item_id, mandatory
* participant_id (so a team or a user-not-in-a-team) or "current-user" mandatory

## Output
List of all paths from root (root_activity|skill_id of groups the user is member of) to the given item that the given participant_id may have used to access this item, so path for which the participant_id has an attempt (possibly ended/not-allowing-submissions) on every item.
Filter paths which are fully visible by the current-user (can_view>=content on every item on the path but the last one can_view>=info).
The item info (title and language_tag) in the paths are in current-user's language, or item's default language if not available.

The order of the paths does not matter.

**Comment by zenovich** [comment]
Why `{ids}` and not `{id}` in the path?

**Comment by zenovich** [comment]
> List of all paths from the input item to a root item (not included)
Why do we want to exclude root items?

**Comment by zenovich** [comment]
> whose the current participant have can_view>=content on every item

Shouldn't it be 'whose the current participant have can_view>=content on every item except the last one and can_view>=info for the last one'?

**Comment by zenovich** [comment]
Are there any restrictions for this service?

**Comment by zenovich** [comment]
Shouldn't we also check that chains of attempts of each path doesn't have missing results for items requiring explicit entry or not started results within or below ended/not-allowing-submissions attempts?

**Comment by smadbe** [comment]
> Why `{ids}` and not `{id}` in the path?

That is a mistake.

> > List of all paths from the input item to a root item (not included)
> 
> Why do we want to exclude root items? Maybe it would make more sense to skip the last item of the path?

Actually, that definition is from before the definition of a path from a base to the item, excluding the base. So use the same definition of path as done for recent services.

> > whose the current participant have can_view>=content on every item
> 
> Shouldn't it be 'whose the current participant have can_view>=content on every item except the last one and can_view>=info for the last one'?

Yes of course

> Are there any restrictions for this service?

I don't see any but the visibility of items.

> Shouldn't we also filter out paths whose chains of attempts have missing results for items requiring explicit entry or not started results within or below ended/not-allowing-submissions attempts?

Good point... actually there are two aspects in this: 
- when listing the paths of an item solved by another user, the point may be to only list those which correspond to the path taken by the user (but it would require a "user" parameter)... actually the user may have different roots as well...
- The current user is not supposed to know the children of an item he has no attempt on. (but that's a bit as `itemPathFromRootFind`)

I need to discuss this with Mathias first. I come back to you asap.

**Comment by smadbe** [comment]
Ok, so:
We need to consider adding a participant as a parameter to the service, which is either the current-user himself (can use "me" or "current-user" or no arg in place of the id) or a participant which is descendant of a group the current-user can manage with can_watch_members.
Return the paths for which the given participants has from his roots to the given item, with can_view>=content access to all and a started attempt AND the current user has can_view>=content on every item on the path but the last one  can_view>=info.

**Comment by zenovich** [comment]
As we do not have '/users/' in our API, I would prefer the URL to be '/items/{item_id}/breadcrumbs-from-roots?participant_id={participant_id}' (where `participant_id` is optional) if you do not mind.

**Comment by zenovich** [comment]
> List of all paths from root (root_activity|skill_id of groups the user is member of)

Which user does it imply? I believe it is participant_id if given and the current user otherwise.

**Comment by smadbe** [comment]
> As we do not have '/users/' in our API, I would prefer the URL to be '/items/{item_id}/breadcrumbs-from-roots?participant_id={participant_id}' (where `participant_id` is optional) if you do not mind.

👍 

> > List of all paths from root (root_activity|skill_id of groups the user is member of)
> 
> Which user does it imply? I believe it is participant_id (if given) and the current user (otherwise).

" I believe it is participant_id (if given) and the current user (otherwise)." 👍
