### ISSUE TITLE
Check itemCreate doc

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#641]
[itemCreate doc](https://france-ioi.github.io/algorea-devdoc/api/#operation/itemCreate) seems to require the input to have an "item" attribute (with an "item" in it?). This is the case and so that's very confusing. 
I don't if it is a mistake or a "bug" for the swagger generator, but we should try to "solve" that.

Also, the "at least one of parent and as_root_of_group_id should be given" constraint is not written in the doc.

**Comment by zenovich** [comment]
The issue related to the "item" attribute has been already fixed in #663
