### ISSUE TITLE
Permission fetching service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#643]
## Overview 
In order to modify the permission in the UI. We need to fetch the existing permissions.

On `GET /groups/{source_group_id}/permissions/{group_id}/{item_id}`

## Input
source_group_id, group_id and item_id

## Output
For each permission (can_view, can_grant_view, ... but can_enter, see below*):
- the granted permission (its minimal value if no entry) on this item, for this group (only) as the given source_group_id and  "group_membership" origin.
- the effective computed permission (its minimal value if no entry) on this item for this group (including ancestors)
- the granted permission (the max of entries, with the minimal value if no entry) on this item, of "group_membership" origin, any source_group_id, on this group and its ancestors, **but excluding** the entry matching the given group + source_group_id 
- the granted permission (the max of entries, with the minimal value if no entry) on this item, of "item_unlocking" origin, any source_group_id, on this group and its ancestors
- same with "self" origin
- same with "other" origin

(\*) As can_enter_\* has not computed permission and works with ranges, return:
- the granted permission (can_enter_from and can_enter_until) on this item, for this group (only) as the given source_group_id and  "group_membership" origin.
- for the effective computed permission, granted permission x4: only return the next time it can enter (i.e. now if we are now in a range, "MIN(can_enter_from among can_enter_from > now)" otherwise)

## Validations
* current user must be manager of the source_group_id with can_grant_group_access
* group must be a descendant of source_group_id
* current user must have can_grant_view > none on item_id

**Comment by zenovich** [comment]
> group must be a descendant of source_group_id

The updatePermissions service checks that the group is a direct child of source_group_id. Shouldn't we do the same here?

**Comment by zenovich** [comment]
> for the effective computed permission, granted permission x4: only return the next time it can enter (i.e. now if we are now in a range, "MIN(can_enter_from among can_enter_from > now)" otherwise)

There is no can_enter_from column in the effective computed permissions table (permissions_generated).

**Comment by zenovich** [comment]
The same question is for `can_make_session_official`

**Comment by smadbe** [comment]
> > group must be a descendant of source_group_id
> 
> The updatePermissions service checks that the group is a direct child of source_group_id. Shouldn't we do the same here?

Direct child... quite strange. In our permissions system, in a hierarchy `school > class > subclass > student` we could have a school giving a permission to a user. But in practice, in the UI, to make things understandable we will only allow the direct parent to give the permission... as it is a decision we made a few weeks ago, the choice of updatePermissions is surprising. 
Ok, do it only with the direct child as that should be the only allowed action from the UI. The "problem" is that our data model allows more than that, so it may still happen... but that's not an actual issue.

> > for the effective computed permission, granted permission x4: only return the next time it can enter (i.e. now if we are now in a range, "MIN(can_enter_from among can_enter_from > now)" otherwise)
> 
> There is no can_enter_from column in the effective computed permissions table (permissions_generated). Should we calculate it somehow anyway for the effective computed permissions basing on granted permissions?

Yes, as it would be an impossible aggregate ranges to a single range, this is the proposed "runtime" aggregation.

> The same question is for `can_make_session_official`

The same. Those are not in "generated perm" table mainly as they do not propagate and so can easily be computed for a given item, group.
