### ISSUE TITLE
Root groups

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#649]
## Overview 
List "root" groups so that we navigate in groups (as we do with items) in the left menu. 

On `GET /groups/roots` ?

## Input
* None (no team_id, no watched group)

## Output
A list of the groups which are ancestors of a joined or managed group and do not have a parent, not considering "type='Base'" groups:
- id
- name
- type
- current_user_membership: none | direct | descendant - whether the user is member of this group or one of its descendants
- current_user_managership: none | direct | ancestor | descendant - whether the user (or its ancestors) is manager of this group, is a manager of one of the ancestor of this group (so is implicitly manager of this group) or, if none but manager of one of the descendants of this group

**Comment by zenovich** [comment]
> whether the user (or its ancestors) is member of this group or one of its descendants

I'm not sure I understand what '(or its ancestors)' means here: if an ancestor is a member of a descendant group, then the group itself is an ancestor of the user too, so at least one child of the group is an ancestor of the user meaning it is a direct membership... So it becomes impossible to get the 'descendant' value for the 'current_user_membership'. If we do not implement this '(or its ancestors)', the 'descendant' value becomes possible.

Also, shouldn't we consider user teams as his ancestor groups everywhere in this task?

**Comment by smadbe** [comment]
> > whether the user (or its ancestors) is member of this group or one of its descendants
> 
> I'm not sure I understand what '(or its ancestors)' means here: if an ancestor is a member of a descendant group, then the group itself is an ancestor of the user too, so at least one child of the group is an ancestor of the user meaning it is a direct membership... So it becomes impossible to get the 'descendant' value for the 'current_user_membership'. If we do not implement this '(or its ancestors)', the 'descendant' value becomes possible.

I think that was a mistake. I removed it. 

> Also, shouldn't we consider user teams as his ancestor groups everywhere in this task?

Good question. Yes you should as the goal is to allow the user to find the groups/teams he belongs to.
