### ISSUE TITLE
Find a group path service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#652]
## Overview 

On `GET /groups/:id/path-from-root`

## Input
* a group_id

## Output
A path as an array of group ids from a visible group root (a **visible** group without non-"base" parent) to the input group. Each group must be visible, so  either 1) ancestors of group he joined, 2) ancestors of group he manages, 3) descendants of group he manages, 4) groups with is_public=1.

Note that if the group_id is a public, none of its parents may be visible by the current user. In this case, this group is the root.

## Validations
* The given group id must be visible as well.

**Comment by zenovich** [comment]
Can the group_id be a 'Base' group?

**Comment by zenovich** [comment]
Can the group_id (:id) represent the current user himself?

**Comment by smadbe** [comment]
> Can the group_id (:id) be a 'Base' group?

No


> Can the group_id (:id) represent the current user himself?

Yes

**Comment by zenovich** [comment]
Can the path contain base groups (we have some base groups having parents in the DB)?

**Comment by zenovich** [comment]
```mysql> select parent.id, parent.type from `groups` join groups_groups_active on groups_groups_active.child_group_id = groups.id join `groups` parent on parent.id = parent_group_id where groups.type='Base';
+--------------------+-------+
| id                 | type  |
+--------------------+-------+
|                  3 | Base  |
| 337433601613235328 | Other |
| 891975878311657173 | Base  |
| 421236451227182626 | Base  |
| 392835294174375388 | Base  |
| 241027385727582636 | Base  |
| 339288625506997544 | Base  |
| 241027385727582636 | Base  |
| 776588495337978448 | Base  |
| 337433601613235328 | Other |
| 339288625506997544 | Base  |
| 223077977181229428 | Base  |
| 961436604110271897 | Base  |
| 938948683689343724 | Base  |
| 130405023994544606 | Base  |
| 533413445282904081 | Base  |
| 776588495337978448 | Base  |
+--------------------+-------+
17 rows in set (0.00 sec)```

**Comment by smadbe** [comment]
No, the path has to go up to (not including) a base group.

**Comment by zenovich** [comment]
> No, the path has to go up to (not including) a base group.

Can a path contain a base group in the middle?

**Comment by smadbe** [comment]
"Up to the first base group" if you prefer. So the path cannot have a base group anywhere.
