### ISSUE TITLE
Fix group-roots / group-navigation services

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#669]
## Motivations
One aspect was missing in the specs: users do not become managers of "users" implicitely.

Let's consider the following group graph, where S_x are schools, Cx are classes, and Ux are users.
```
          S1       S2
        /    \   /    \
       C1     C2       C3
      / \    /  \     /   \
    U1    U2       U3      U4
```
Case 1 (handled correctly): If the current user is the manager (himself or through one of his ancestors, it does not matter) of S1, it is implicitly manager of C1, C2... so the following groups are visible to him: S1, C1, C2, U1, U2, U3, S2 (as a group which is an ancestor of C2 he manages).

Case 2 (not handled correctly): If the current user is the manager (himself or through one of his ancestors, it does not matter) of C2, he does not become manager of U2 and U3, the following groups are visible to him: C2, S1, S2, U2, U3. He does see C1 or C3.

## Subtasks
* fix the group-roots and group-navigation services so that case 2 is correctly handled

**Comment by zenovich** [comment]
> Case 1 (handled correctly): If the current user is the manager (himself or through one of his ancestors, it does not matter) of S1, it is implicitly manager of C1, C2... so the following groups are visible to him: S1, C1, C2, U1, U2, U3, S2 (as a group which is an ancestor of C2 he manages).

Shouldn't C3 be visible too as an ancestor of U3 which is managed by the current user?

**Comment by zenovich** [comment]
So we go up only from non-user groups?

**Comment by smadbe** [comment]
> > Case 1 (handled correctly): If the current user is the manager (himself or through one of his ancestors, it does not matter) of S1, it is implicitly manager of C1, C2... so the following groups are visible to him: S1, C1, C2, U1, U2, U3, S2 (as a group which is an ancestor of C2 he manages).
> 
> Shouldn't C3 be visible too as an ancestor of U3 which is managed by the current user?

No as "users do not become managers of "users" implicitely.", that the whole point.

> So we go up only from non-user groups?

Basically, yes.
