### ISSUE TITLE
Apply new group visibility rules to all group services

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#677]
## Motivations
Apply these rules in a consistent way on all services, both in implementation and doc/spec

## Subtasks
Apply the latest group visibility rules:

>  1) ancestors of groups he joined, 2) ancestors of non-user groups he manages, 3) descendants of groups he manages, 4) groups with is_public=1. 

On all implementations and doc/spec:
- groupGet
- groupChildrenView ->  ~the authenticated user should be a manager of the parent group~, if the given group id is visible, list visible children,
- groupNavigationView (at least doc is not fully correct)
- groupBreadcrumbsView (at least doc is not fully correct)
- groupRootsView (at least doc is not fully correct)

**Comment by zenovich** [comment]
> groupChildrenView -> the authenticated user should be a manager of the parent group, if the given group id is visible, list visible children

This service exposes group codes, so it should be rewritten (at least a bit) in order to allow usage by non-managers.

**Comment by zenovich** [comment]
> groupRootsView (at least doc is not fully correct)

I think there was some reason for skipping public groups which are not ancestors of joined/managed groups in this service. At least, public groups were never mentioned in the specs of the service.

**Comment by smadbe** [comment]
> > groupChildrenView -> the authenticated user should be a manager of the parent group, if the given group id is visible, list visible children
> 
> This service exposes group codes, so it should be rewritten (at least a bit) in order to allow usage by non-managers.

I think that will be required, yes. 👍 

> > groupRootsView (at least doc is not fully correct)
> 
> I think there was some reason for skipping public groups which are not ancestors of joined/managed groups in this service. At least, public groups were never mentioned in the specs of the service.

👍  Right, public groups should be skipped for this service.

**Comment by smadbe** [comment]
`groupChildrenView` can be edited this way:
* can_* are still useful
* `code` should be removed
* `user_count`  should only be given for managers (whatever the level is)
