### ISSUE TITLE
group update: update required permissions

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#678]
## Motivations
Now we have different level of managership, adapt these to the old group-update service

## Subtasks
* Require "membership" level to change:
  - code_expires_at
  - code_lifetime
  - frozen_membership
* Require "membership+group" level for the attributes.
* Add other attributes which have been added in the meantime:
  - require_*_approval* (Require "membership+group" level)
  - require_members_to_join_parent (Require "membership+group" level)
  - max_participants (Require "membership")
  - enforce_max_participants  (Require "membership")

**Comment by zenovich** [comment]
So, we require "memberships" level to change code_expires_at, code_lifetime, frozen_membership, max_participants, enforce_max_participants. For changing other fields we require "memberships_and_group". Correct?

Should we allow setting a field to the same value for those who don't have the required level of managership?

Are there any fields for which we want to allow setting to lower values without requiring any level of managership?

**Comment by smadbe** [comment]
> So, we require "memberships" level to change code_expires_at, code_lifetime, frozen_membership, max_participants, enforce_max_participants. For changing other fields we require "memberships_and_group". Correct?

correct

> Should we allow setting a field to the same value for those who don't have the required level of managership?

good point, yes 
 
> Are there any fields for which we want to allow setting to lower values without requiring any level of managership?

I do not see any.
