### ISSUE TITLE
groupRemoveChild: remove the orphan check

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#682]
## Motivations
The workflow for removing subgroup has changed, adapt the service

## Subtasks
In [groupRemoveChild](https://france-ioi.github.io/algorea-devdoc/api/#operation/groupRemoveChild) service:
- if the deletion would create an orphan and delete_orphans=0, do not fail with 422 but just delete it.

**Comment by zenovich** [comment]
> if the deletion would create an orphan and delete_orphans=0, do not fail with 422 but just delete it.

What should it delete, the group relation or the child group?

**Comment by smadbe** [comment]
Just delete the relation without removing the child group in this case.
