### ISSUE TITLE
item dependencies edition services

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#694]
## Overview 
Allow creation and deletion of dependencies between items

On `POST /items/{dependent_item_id}/prerequisites/{prerequisite_item_id}`
and `DELETE /items/{dependent_item_id}/prerequisites/{prerequisite_item_id}`

### For creation:
- dependent_item_id, prerequisite_item_id
- score (optional)
- grant_content_view 
### For deletion:  
- dependent_item_id, prerequisite_item_id

## Validations/Restrictions
For creation, current-user must have:
- can_view>=info on prerequisite_item_id
- can_edit=all on dependent_item_id
- if input.grant_content_view,  can_grant_view >= content on the dependent_item_id
- prerequisite_item_id may be the same as dependent_item_id
- no constraints on the item type

For deletion, current-user must have:
- can_edit=all on dependent_item_id

## Actions
Create/delete relation. 

Do not create/delete view access based on the changed rules.

## Output
Generic output

**Comment by zenovich** [comment]
Done in #748
