### ISSUE TITLE
itemChildrenView: add dependencies

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#697]
## Motivations
In order to display, [in the list of children, a "key" icon which indicates that this item unlocks other ones](https://france-ioi.github.io/algorea-designs/03.Activities_01.Content__structure), add this information in the service

## Subtasks
In [itemChildrenView](https://france-ioi.github.io/algorea-devdoc/api/#operation/itemChildrenView):
- add in output: `grant_access_to_other_items`: whether solving this item grant access to other items (visible or not)

**Comment by zenovich** [comment]
As it is a possible situation where item_dependencies.item_id = item_dependencies.dependent_item_id, should we ignore such dependencies on calculation of grant_access_to_other_items or just rename the field (for example, to grants_access_to_items, so it wouldn't contain the word 'other')?

**Comment by smadbe** [comment]
I must admit I do not find the usecase where `item_dependencies.item_id = item_dependencies.dependent_item_id` is useful.
Do you remember?

I would say: do not ignore "item_dependencies.item_id = item_dependencies.dependent_item_id".

**Comment by zenovich** [comment]
> I must admit I do not find the usecase where `item_dependencies.item_id = item_dependencies.dependent_item_id` is useful.
> Do you remember?
> 
> I would say: do not ignore "item_dependencies.item_id = item_dependencies.dependent_item_id".

It is from #694 where we have a requirement: `prerequisite_item_id may be the same as dependent_item_id`

**Comment by smadbe** [comment]
Yes, I saw, but I don't remember why.  
Ah I think I didn't understand your point on naming last time: `grants_access_to_items` looks good as name.
I do not find `grant_access_to_other_items` in the project? What is it already?

**Comment by zenovich** [comment]
> Yes, I saw, but I don't remember why.
> Ah I think I didn't understand your point on naming last time: `grants_access_to_items` looks good as name.
> I do not find `grant_access_to_other_items` in the project? What is it already?

`grant_access_to_other_items` is the new field described in this task:
```
add in output: grant_access_to_other_items: whether solving this item grant access to other items (visible or not)
```

**Comment by zenovich** [comment]
So it should be `grants_access_to_items`, right?

**Comment by smadbe** [comment]
> the new field described in this task:

🤦🏻‍♂️ ok sorry


> So it should be `grants_access_to_items`, right?

Yes
