### ISSUE TITLE
Do not require the watched group to view the item to list it in activitiesView

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#738]
## Motivations
In the activitiesView service with `watched_group_id`, most groups does not any activities returned as it requires both the current user and the watched group to have access to the item. The need for the watched group to have access is not that important as group members may have access by other means (for instance, "all users" group).

## Subtasks
Remove the requirement for the watched group to be allowed to view an item for it to be listed in the `activitiesView` service with `watched_group_id` parameter.

Same for skillsView

Same for itemNavigationView

**Comment by zenovich** [comment]
In activitiesView we display permissions which the watched group has on items, should we keep this behaviour or display permissions the current user has instead?

**Comment by smadbe** [comment]
Probably permission of the current user are more useful.

**Comment by zenovich** [comment]
There is no such issue in itemNavigationView
