### ISSUE TITLE
Measure time spent by a lightweight group*Progress service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#750]
On current data, the worst case scenario in production for a user who has to observe a group is: user 670968966872011405 observing group 437252577785336049 on item 1980584647557587953.

This is request takes 7.5s, it is not yet dramatic, but it is not fast. (ah but the service returns max 1000 entries while this one has 1555 users * 15 items, so possibly 23k entries...  In practice: need 5 more sec to get the second and last part)

Could you measure how much time it would take for the same request if only score and validated are outputted. (so not `hints_requested`, `latest_activity_at`, submissions, time_spent) ?

**Comment by zenovich** [comment]
When groupUserProgress returns only `score` and `validated`, it takes only 879ms on my computer to return the first page of results.

**Comment by zenovich** [comment]
On the other, hand the original groupUserProgress service (without modifications) take less than a second on my computer too. Also, on dev.algorea.org it took about 3 seconds to respond: ```0.03s user 0.04s system 1% cpu 3.275 total```

**Comment by zenovich** [comment]
Which one of group*Progress services do you mean in this task?

**Comment by zenovich** [comment]
I tried this one ```https://dev.algorea.org/api/groups/437252577785336049/user-progress?parent_item_ids=1980584647557587953```

**Comment by zenovich** [comment]
<img width="669" alt="Screenshot 2021-06-09 at 09 06 08" src="https://user-images.githubusercontent.com/135378/121302289-27378680-c902-11eb-8dbd-050808f753d0.png">

**Comment by zenovich** [comment]
I saw it took the UI more than 10 seconds to draw the results

**Comment by smadbe** [comment]
```
$ time curl 'https://dev.algorea.org/api/groups/437252577785336049/user-progress?parent_item_ids=1980584647557587953&limit=5000001' -H 'Authorization: Bearer ***' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2716k  100 2716k    0     0   338k      0  0:00:08  0:00:08 --:--:--  577k

real	0m8.039s
user	0m0.069s
sys	0m0.096s
```

**Comment by smadbe** [comment]
> When groupUserProgress returns only `score` and `validated`, it takes only 879ms on my computer to return the first page of results.

> On the other, hand the original groupUserProgress service (without modifications) take less than a second on my computer too. Also, on dev.algorea.org it took about 3 seconds to respond: `0.03s user 0.04s system 1% cpu 3.275 total`

So your conclusion is that it takes the same time with and without all the more complex attributes?

**Comment by zenovich** [comment]
> > When groupUserProgress returns only `score` and `validated`, it takes only 879ms on my computer to return the first page of results.
> 
> > On the other, hand the original groupUserProgress service (without modifications) take less than a second on my computer too. Also, on dev.algorea.org it took about 3 seconds to respond: `0.03s user 0.04s system 1% cpu 3.275 total`
> 
> So your conclusion is that it takes the same time with and without all the more complex attributes?

Yes, and in both cases the time is less than 3 seconds. But it can take the UI more than 30 seconds to render the results

**Comment by zenovich** [comment]
I measured the response time again (with restarting MySQL before each measuring):

1. For the unpatched version of groupUserProgress:
1508.447064ms
1247.493739ms
1233.048603ms
1274.97175ms
1239.025669ms

2. For the patched version of groupUserProgress where we return only `score` and `validated`:
819.442501
827.86395
853.101309
832.010027
880.869999

Now we can see there is a difference, though small.
(After installing some updates my computer started working much faster (don't know why) and this is why the new timings are much better).

**Comment by zenovich** [comment]
The same measurements, but with limit=1000:
unpatched:
2329.712898ms
2423.134623ms
2417.934445ms
2592.282042ms
2445.919732ms
patched:
1464.891665ms
1605.474518ms
1691.394113ms
1570.095851ms
1550.433862ms

**Comment by zenovich** [comment]
The same measurements, but with limit=1000 and sql logs turned off in config.yaml:
unpatched:
1966.793864ms
1979.385668ms
1957.792449ms
1933.009612ms
1974.397119ms
patched:
1146.969929ms
1109.33626ms
1087.048619ms
1098.306122ms
1080.807525ms

**Comment by zenovich** [comment]
Can we close this one? @smadbe

**Comment by smadbe** [comment]
Yes, let's close this one for the moment.
