### ISSUE TITLE
Participant progress service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#751]
## Overview 
In addition to existing group*progress service, we need a service to get the same data for a specific user or team. 
![Screenshot 2021-06-07 at 16 28 41](https://user-images.githubusercontent.com/1053150/121034611-6e603300-c7ad-11eb-8273-195fc43865f2.png)

On `GET /???`

## Input
* a participant_id which is either a user or a team
* item_id
* as_team_id

## Output
The list of (visible) children of the input item, with:

as in itemChildrenView:
* item_id
* no_score
* permissions
* string
* type

as in groupUserProgress:
* hints_requested
* latest_activity_at
* score
* submissions
* time_spent
* validated

Sorted by children order only.

## Validations
* the input group has to be a participant (user or team)
* the current user must be either the participant himself (as a user or with `as_team_id`) or [ allowed to watch the participant + allow to watch result of each of the children of the item (same as groupUserProgress) ]
* the current user must be allowed to list children of the input item_id

**Comment by zenovich** [comment]
> type
(as in groupUserProgress)

There is no such field `type` in groupUserProgress. What was meant here?

**Comment by zenovich** [comment]
> permissions
Should we return permissions for the current user or for the participant?

**Comment by zenovich** [comment]
> Input

> a group_id which is either a user or a team
> item_id

> the current user must be either the participant himself (as a user or with as_team_id) or allowed to watch the participant + allow to watch result of each of the children of the item (same as groupUserProgress)

So either we should add `as_team_id` to the input or fix the validation description. Which one is correct?

**Comment by smadbe** [comment]
> > type
> > (as in groupUserProgress)
> 
> There is no such field `type` in groupUserProgress. What was meant here?

It was a wrong indentation done by the GH. I've fixed it. It is the type of the item.

> > permissions
> 
> Should we return permissions for the current user or for the participant?

Good question. Should be current user's. Maybe calling this attribute `current_user_permissions` would make things clearer.



> > Input
> 
> > a group_id which is either a user or a team
> > item_id
> 
> > the current user must be either the participant himself (as a user or with as_team_id) or allowed to watch the participant + allow to watch result of each of the children of the item (same as groupUserProgress)
> 
> So either we should add `as_team_id` to the input or fix the validation description. Which one is correct?

Fixed. There should be a `as_team_id` input.

**Comment by zenovich** [comment]
>a group_id which is either a user or a team
as_team_id

Anyway it seams to be inconsistent with other service: we have either `group_id` (as in groupUserProgress) or one of `as_team_id`&`watched_group_id` (as in activitiesView). A combination of `group_id` & `as_team_id` is something new.
I suggest using `as_team_id`+`watched_group_id` here (one or none can be used).

**Comment by zenovich** [comment]
> the current user must be allowed to list children of the input item_id
I don't get this phrase. Should we check access rights for the item_id or show only those children of item_id which are visible to the current user? Should we consider items with `can_view`>='info' as visible or `can_view`>='info' is okay here?

**Comment by zenovich** [comment]
Should we include subtitles into response[i].String?

**Comment by smadbe** [comment]
> > a group_id which is either a user or a team
> > as_team_id
> 
> Anyway it seems to be inconsistent with other services: we have either `group_id` (as in groupUserProgress) or one of `as_team_id`&`watched_group_id` (as in activitiesView). A combination of `group_id` & `as_team_id` is something new.
> I suggest using `as_team_id`+`watched_group_id` here (one or none can be given), but maybe I don't get something...

That's not the same. The current user tries to get the result of a given participant and its either himself or a participant he is allowed to watch. 
On the other side, `as_team_id` is about who you are acting as, so either yourself or a team you belong to.
Finally, `watched_group_id ` is for regular services, to request extra data related with a group you are currently observing (you want to see the app as a given group you are allowed to observe).

> > the current user must be allowed to list children of the input item_id
> 
> I don't get this phrase. Should we check access rights for the item_id or show only those children of item_id which are visible to the current user? Should we consider items with `can_view`>='content' as visible or `can_view`>='info' is okay here (like in groupUserProgress)?
> And when `watched_group_id` is given, we can just exclude items with `can_watch` < 'result', right?

I just mean the user must have `can_view`>='content'  on the input `item_id`, which is required to list the children of an item. In addition, you  `can_view`>='info' on each children to list it. It should be what's done for the children list service.

> Should we include subtitles into response[i].String (as in itemChildrenView)?

Probably not.

**Comment by smadbe** [comment]
Now I re-view the `itemActivityLogForAllItems` service, if you prefer, you can do the same: i.e not take the participant_id as regular input and return the progress of the current-user if `watched_group_id` is not given, and return the progress of `watched_group_id` if given. 
As you prefer.

**Comment by zenovich** [comment]
Should we allow pagination here?

**Comment by zenovich** [comment]
Should we allow multiple parent item IDs?

**Comment by smadbe** [comment]
> Should we allow pagination here?

I don't see the point in this service.

> Should we allow multiple parent item IDs?

No (at least for now)
