### ISSUE TITLE
Answer and state can be empty strings

### ISSUE THREAD

**Issue by mblockelet** [France-ioi/AlgoreaBackend#759]
Contrary what is required in the answerData type, answer and state can each be empty strings depending on the task. I think the requirement should be removed, unless there is a good reason to keep it.

https://github.com/France-ioi/AlgoreaBackend/blob/36de42f55ea25242a94a143957b8f221d23873f6/app/api/answers/answers.go#L18-L25

**Comment by zenovich** [comment]
@smadbe Should we remove "minLength: 1" or keep it?

**Comment by smadbe** [comment]
Ok, look correct. I don't remember why we enforced this "min 1 length" rule.

**Comment by smadbe** [comment]
@mblockelet does it have to be fixed for the SNT test?

**Comment by mblockelet** [comment]
@smadbe It's not mandatory, but would be better if it is fixed before.

**Comment by smadbe** [comment]
Ok so @zenovich , try to work on this in priority.
