### ISSUE TITLE
Various improvements to group code lifetime

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#768]
## Overview
When testing the platform with actual user, we notice some aspects of the group code lifetimes which need to be improved.

## Acceptance criteria
- [ ] The current data structure for storing the code lifetime is a mysql "time" whose max value is '838:59:59' which is only <35days. It should be possible to set it to 1 year. Strictly negative value is not relevant, nor sub-second values. 
- [ ] It should be possible to express "infinite".
- [ ] "0" is valid, it means that the code is usable once (expires at its first usage)
- [ ] Infinite should be the default value
- [ ] In the legacy data, all "0" are actually 'infinite'.

**Comment by zenovich** [comment]
> In the legacy data, all "0" are actually 'infinite'.

There are no rows with code_lifetime = '00:00:00' in the anonymized DB:
```
select count(*) from `groups` where code_lifetime ='00:00:00';
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```
