### ISSUE TITLE
In group*Progress (inc.  groupParticipantProgress): add root results

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#780]
## Overview

All these services have a common issue in practice (in terms of UI/usability), there are missing an entry for the "root" item id (the one given as arg), we display the outcome for every children but not the item of concern itself (and due to the weight, no score etc, it might not just be a sum).

Probably the "best" solution could be to add the root to the list. In group/user/team progress, it could just be just added to the list, in `groupParticipantProgress`, we could modify the array to a dictionary of root result (no need for the string, no_score, permissions, type) + children.

## Acceptance criteria
- [ ] in group/user/team progress, include the input items in the output
- [ ] in groupParticipantProgress, transform the array to a dictionary with the root "results" and the "children" results (as an array).

**Comment by zenovich** [comment]
How to combine this with pagination in group/user/team progress? (Currently we have json array row for each table cell, and we paginate by rows, i.e. child items. So if we mix parent and child items together, the page can end right after a parent item while its children are on the next).

**Comment by smadbe** [comment]
The parent row should be before its children. The pagination with the multiple parent item_id is non sense anyway. (I really thing we should stop supporting these multiple item_id, should we do this now?)

**Comment by zenovich** [comment]
Okay. Should we still support multiple parent items for CSV?

**Comment by smadbe** [comment]
As I already answered somewhere else (I think): no

**Comment by zenovich** [comment]
Okay, I'll remove support for multiple parent_item_ids. But still the question: when pagination is used, should we include the parent item as the first row of all the pages?

**Comment by zenovich** [comment]
Sorry for my messy question above :( . As we paginate over participants (not over items), root items inclusion doesn't affect pagination. Also, we can keep supporting multiple parent_item_ids.

**Comment by smadbe** [comment]
ok 🤷‍♂️
