### ISSUE TITLE
List granted permissions

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#783]
## Overview 
In order to have an overview of the permissions given to group/user, list all granted permissions.

On `GET /groups/{group_id}/granted_permissions`

Sort by item title ? (beware at the items without title)

## Input
* group_id
* descendants: boolean (default 0)

## Output
[if descendants = 0] For every granted permissions given by (= with as a source group) the group or one of its ancestors on which the current-user has can_grant_group_access, to the group or its ancestors, ...

[if descendants = 1] For every granted permissions given by (= with as a source group) the group, its ancestors+descendants`*` on which the current-user has can_grant_group_access, to its descendants (not including the group itself), ...

... , AND only if the current user can grant permissions to the item ('can_grant_view' >= 'enter' or can*='..with_grant'), return:

* group: id, name 
* source_group_id: id, name
* item: id, title, language tag, require_explicit_entry
* permissions

## Validations
* The current user (or one its ancestors) must be allowed to grant permissions (so at least 'can_grant_group_access'=true) to the given group or one of its ancestors.
* (`*`) Reminder: the managing permission propagates from group to its descendants, but not to participants, so a school see permissions with, as source group, a class of this school, but not with, as source group, a student.

**Comment by zenovich** [comment]
Currently we have the permissionsView service (/groups/{source_group_id}/permissions/{group_id}/{item_id}) which returns granted and generated permissions given by source_group_id to group_id on item_id. For given parameters, granted permissions with each 'origin' are returned separately.

In this new service, we have only one parameter (group_id). Does this mean we want to list all the combinations of source_group_id - item_id pairs (where source_group_id is an ancestor of group_id (or an ancestor/descendant when descendants=1)? Also, do we want to merge permissions from all the origins together or return them similarly to what permissionsView does or list all the combinations of source_group_id - item_id - origin instead?
@smadbe

**Comment by smadbe** [comment]
> Currently we have the permissionsView service (/groups/{source_group_id}/permissions/{group_id}/{item_id}) which returns granted and generated permissions given by source_group_id to group_id on item_id. For given parameters, granted permissions with each 'origin' are returned separately.
> 
> In this new service, we have only one parameter (group_id). Does this mean we want to list all the combinations of source_group_id - item_id pairs (where source_group_id is an ancestor of group_id (or an ancestor/descendant when descendants=1)? 

No, that is not the same service at all. The other one returns the granted (possibly void) & computed perm for a given group and item. Here we want to list all the items which have specific (not default, at least one not at the minimum) granted permission so that we can try to understand what perm has been given to a group.

> Also, do we want to merge permissions from all the origins together or return them similarly to what permissionsView does or list all the combinations of source_group_id - item_id - origin instead?

Just return all permissions matching the given group. So aggregation to be done.

**Comment by zenovich** [comment]
> The current user (or one its ancestors) must be allowed to grant permissions to the given group (implicitly or explicitly)

Does this mean the current user (or at least one of his ancestors) must be a manager of at least one of the group's ancestors (excluding the group itself) with 'can_grant_group_access' >= 'enter'?
@smadbe

**Comment by zenovich** [comment]
> > Currently we have the permissionsView service (/groups/{source_group_id}/permissions/{group_id}/{item_id}) which returns granted and generated permissions given by source_group_id to group_id on item_id. For given parameters, granted permissions with each 'origin' are returned separately.
> > In this new service, we have only one parameter (group_id). Does this mean we want to list all the combinations of source_group_id - item_id pairs (where source_group_id is an ancestor of group_id (or an ancestor/descendant when descendants=1)?
> 
> No, that is not the same service at all. The other one returns the granted (possibly void) & computed perm for a given group and item. Here we want to list all the items which have specific (not default, at least one not at the minimum) granted permission so that we can try to understand what perm has been given to a group.
> 
> > Also, do we want to merge permissions from all the origins together or return them similarly to what permissionsView does or list all the combinations of source_group_id - item_id - origin instead?
> 
> Just return all permissions matching the given group. So aggregation to be done.

So still all source_group_id-item_id pairs, right? (otherwise it is not obvious how source_group_id could be returned)
@smadbe

**Comment by smadbe** [comment]
> > The current user (or one its ancestors) must be allowed to grant permissions to the given group (implicitly or explicitly)
> 
> Does this mean the current user (or at least one of his ancestors) must be a manager of at least one of the group's ancestors (excluding the group itself) with 'can_grant_group_access' >= 'enter'?

Yes. 
But why "excluding the group itself" ?

> So still all source_group_id-item_id pairs, right? (otherwise it is not obvious how source_group_id could be returned)

Yes

**Comment by zenovich** [comment]
> > > The current user (or one its ancestors) must be allowed to grant permissions to the given group (implicitly or explicitly)
> > 
> > 
> > Does this mean the current user (or at least one of his ancestors) must be a manager of at least one of the group's ancestors (excluding the group itself) with 'can_grant_group_access' >= 'enter'?
> 
> Yes.
> But why "excluding the group itself" ?

There are two reasons:
1. The description of `group_managers.can_grant_group_access` is "Can give members access rights to some items (requires the giver to be allowed to give this permission on the item)". As I understand this, it can be applied only to descendant groups ("members"), not to the group itself.
2. Other existing services (updatePermissions, permissionsView) check that the current user has 'can_grant_group_access'>='enter' on a parent group of `group_id` (see https://github.com/France-ioi/AlgoreaBackend/issues/643#issuecomment-755219360 and https://github.com/France-ioi/AlgoreaBackend/issues/643).

**Comment by smadbe** [comment]
> > But why "excluding the group itself" ?
> 
> There are two reasons:
> 
>     1. The description of `group_managers.can_grant_group_access` is "Can give members access rights to some items (requires the giver to be allowed to give this permission on the item)". As I understand this, it can be applied only to descendant groups ("members"), not to the group itself.

Giving permissions to a group results in giving permissions to the members, so it is just a way to give perm access to all members at once. So that is a misunderstanding.
 
>     2. Other existing services (updatePermissions, permissionsView) check that the current user has 'can_grant_group_access'>='enter' on a parent group of `group_id` (see [Permission fetching service #643 (comment)](https://github.com/France-ioi/AlgoreaBackend/issues/643#issuecomment-755219360) and [Permission fetching service #643](https://github.com/France-ioi/AlgoreaBackend/issues/643)).

If it is, that's a mistake. 

What I tried to say in that comment was that, in theory, in a `G1 > G2 > G3 > U1" hierarchy, the manager of G2 is able to give perm to U1 with G2 or G3 as source group, but we could consider that we'll always give it as G3 as subgroup for now.

Probably I should write a new issue fixing that.

> Maybe it should even be "the current user (or at least one of his ancestors) must be a manager of at least one of the group's children with 'can_grant_group_access' >= 'enter'?"

The current user (or one of his ancestors) must be a manager of at least one of the group's **ancestors** (including itself) with 'can_grant_group_access' >= 'enter'?"

**Comment by zenovich** [comment]
Should we return a result row for each permissions_granted row (with different origins) or group rows having common source_group_id-group_id-item_id triad together somehow? @smadbe

**Comment by zenovich** [comment]
The spec says that when `descandants`=0 we only want to display permissions granted by ancestors of the given `group_id`. Knowing that we require source groups to be ancestors of target groups in `updatePermissions`, it looks correct. But what if after a group relation is deleted, a source group is not an ancestor of a target group anymore. The given permissions are still active, but there is no way to see them via AlgoreaBackend's API anymore. I suggest showing all the granted permissions given by groups managed by the current user regardless of ancestry relations between the source group and the target group.
Also, when `descendants`=0, there can be a situation where a permission comes to a descendant of `group_id` from some its ancestor which is neither a descendant, nor an ancestor of `group_id`. If we implement grantedPermissionsView according to the current spec, it will not display such permissions. In this case, removing the requirement related to ancestry-relations between the source group and `group_id` would help too. @smadbe

**Comment by zenovich** [comment]
The spec says "The current user (or one its ancestors) must be allowed to grant permissions (so at least 'can_grant_group_access' >= 'enter') to the given group or one of its ancestors". As 'can_grant_group_access' can only be true or false, I think you wanted to say 'can_grant_group_access' should be true and, at the same time, the current user should have at least 'can_grant_view' >= 'enter' on items we display.
At the same time, looking at the updatePermissions service, I see that we allow changing 'can_watch' and 'can_edit' permissions even if 'can_grant_view' of the current user is 'none'. So probably it would make sense to display permissions in grantedPermissionsView not only when the current user has 'can_grant_view' >= 'enter', but also when the current user has 'can_watch'='answer_with_grant' or 'can_edit'='all_with_grant'. @smadbe

**Comment by smadbe** [comment]
> The spec says that when `descandants`=0 we only want to display permissions granted by ancestors of the given `group_id`. Knowing that we require source groups to be ancestors of target groups in `updatePermissions`, it looks correct. But what if after a group relation is deleted, a source group is not an ancestor of a target group anymore. The given permissions are still active, but there is no way to see them via AlgoreaBackend's API anymore. I suggest showing all the granted permissions given by groups managed by the current user regardless of ancestry relations between the source group and the target group. 

Seems fine to me. (BTW, in the example you give, the permission should be removed when the group-group relation is deleted. )

> Also, when `descendants`=0, there can be a situation where a permission comes to a descendant of `group_id` from some its ancestor which is neither a descendant, nor an ancestor of `group_id`. If we implement grantedPermissionsView according to the current spec, it will not display such permissions. In this case, removing the requirement related to ancestry-relations between the source group and `group_id` would help too. 

Do you mean , when `descendants`=1 ? When `descendants`=0, descendants should not be considered
Here, the goal of this service is to display the permissions granted by the given group (and its ancestor), not to show the actual resulting permissions.

> The spec says "The current user (or one its ancestors) must be allowed to grant permissions (so at least 'can_grant_group_access' >= 'enter') to the given group or one of its ancestors". As 'can_grant_group_access' can only be true or false, I think you wanted to say 'can_grant_group_access' should be true and, at the same time, the current user should have at least 'can_grant_view' >= 'enter' on items we display. 

Right. Spec fixed.

> At the same time, looking at the updatePermissions service, I see that we allow changing 'can_watch' and 'can_edit' permissions even if 'can_grant_view' of the current user is 'none'. So probably it would make sense to display permissions in grantedPermissionsView not only when the current user has 'can_grant_view' >= 'enter', but also when the current user has 'can_watch'='answer_with_grant' or 'can_edit'='all_with_grant'. 

You're right. I think that's a mistake when I wrote the spec (I forgot about 'answer_with_grant' and 'all_with_grant')

**Comment by zenovich** [comment]
> > The spec says that when `descandants`=0 we only want to display permissions granted by ancestors of the given `group_id`. Knowing that we require source groups to be ancestors of target groups in `updatePermissions`, it looks correct. But what if after a group relation is deleted, a source group is not an ancestor of a target group anymore. The given permissions are still active, but there is no way to see them via AlgoreaBackend's API anymore. I suggest showing all the granted permissions given by groups managed by the current user regardless of ancestry relations between the source group and the target group.
> 
> Seems fine to me. (BTW, in the example you give, the permission should be removed when the group-group relation is deleted. )

We do not remove permissions when a group-group relation is deleted (There is no anything related to that either in the code or in DB triggers).

> > Also, when `descendants`=0, there can be a situation where a permission comes to a descendant of `group_id` from some its ancestor which is neither a descendant, nor an ancestor of `group_id`. If we implement grantedPermissionsView according to the current spec, it will not display such permissions. In this case, removing the requirement related to ancestry-relations between the source group and `group_id` would help too.
> 
> Do you mean , when `descendants`=1 ? When `descendants`=0, descendants should not be considered Here, the goal of this service is to display the permissions granted by the given group (and its ancestor), not to show the actual resulting permissions.
> 

Yes, I meant `descendants`=1 here. Maybe, if the goal is to display permissions granted by the given group, it would make even more sense to the remove requirements related to ancestry-relations between the source group and `group_id`. What do you think?

> > The spec says "The current user (or one its ancestors) must be allowed to grant permissions (so at least 'can_grant_group_access' >= 'enter') to the given group or one of its ancestors". As 'can_grant_group_access' can only be true or false, I think you wanted to say 'can_grant_group_access' should be true and, at the same time, the current user should have at least 'can_grant_view' >= 'enter' on items we display.
> 
> Right. Spec fixed.
> 
> > At the same time, looking at the updatePermissions service, I see that we allow changing 'can_watch' and 'can_edit' permissions even if 'can_grant_view' of the current user is 'none'. So probably it would make sense to display permissions in grantedPermissionsView not only when the current user has 'can_grant_view' >= 'enter', but also when the current user has 'can_watch'='answer_with_grant' or 'can_edit'='all_with_grant'.
> 
> You're right. I think that's a mistake when I wrote the spec (I forgot about 'answer_with_grant' and 'all_with_grant'). Spec fixed.

Thanks. I will update the code. The permissionsView service has the same issue.
