### ISSUE TITLE
Get item: add watched group permissions

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#785]
## Overview
In order to display the group permissions to the observer, add the group permissions to the get-item service.

## Acceptance criteria
For get-item service: 
- [ ] if `watched_group_id` is given, add a `watched_group` tuple with:
  - [ ] the (computed) `permissions` of the watched group on the item to the service. 
  - [ ] the `average_score` (as defined in `groupGroupProgress`, i.e. the avg score of participant (or of the team/user directly if the watched group is a team or a user)
- [ ] forbidden if the current user cannot watch the given group id
- [ ] not returned if the current user cannot see these permissions. The user can see the permissions IF:
   - he can watch the group and can watch the item, OR
   - he can grant perm to the group and can grant perm to the item

**Comment by zenovich** [comment]
Currently itemView displays the best score of the user (or as_team_id). Should it display the best score of the watched_group_id when it is given instead?
@smadbe

**Comment by zenovich** [comment]
Also, should we still show permissions for the user (as_team_id) when watched_group_id is given?
@smadbe

**Comment by smadbe** [comment]
> Currently itemView displays the best score of the user (or as_team_id). Should it display the best score of the watched_group_id when it is given instead?

That's something else, but sure we will need that as well. So they may all be in a "watched_group" subtuple (with `best_score`, `permissions`) as you did for another service.

> Also, should we still show permissions for the user (as_team_id) when watched_group_id is given?

 yes
