### ISSUE TITLE
Operation `membershipsView` wrong group type

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaBackend#795]
In the [`membershipsView` operation documentation](https://france-ioi.github.io/algorea-devdoc/api/#operation/membershipsView), the group type is `"Class" "Team" "Club" "Friends" "Other" "Base"`

However the backend returns `"Session"` groups as well. So either the doc is stale, either the `membershipsView` service has a bug. @smadbe what should be done ?

See the second results of the request below:

```bash
curl 'https://dev.algorea.org/api/current-user/group-memberships' \
  -H 'authority: dev.algorea.org' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Chromium";v="93", " Not;A Brand";v="99"' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'authorization: Bearer **' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'origin: http://localhost:4200' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:4200/' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed
```

**Comment by smadbe** [comment]
It is just a small bug (to be fixed) in the doc. I think sessions have been added after the creation of this service and the doc has not been updated.
