### ISSUE TITLE
Get answer: let observers call the service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#806]
## Overview

Users observing a group and having the appropriate permissions should be able to call this service. The [current spec](https://france-ioi.github.io/algorea-devdoc/api/#operation/answerGet) indicates only participants should be able to call this service.

## Acceptance criteria
- [ ] If current-user has [`can_watch>=answer`](https://france-ioi.github.io/algorea-devdoc/design/access-rights/items/#can_watch) on the item and watch permission on the participant (so manager with `can_watch_members` of an ancestor of the participant), he should be able to get an answer
- [ ] the current case should still be supported (a user should still be able to see his own answer)

**Comment by zenovich** [comment]
>  If current-user has can_watch>=answer on the item and watch permission on the participant (so manager with can_watch_members of an ancestor of the participant), he should be able to get an answer

Should this work when the participant is a user? (IMO it should not) @smadbe
