### ISSUE TITLE
Activity log: include other types of answer

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#807]
## Motivations

In log views, we are interested in displaying saved and current answer so that we can load them.

## Subtasks

In the [itemActivityLogForItem](https://france-ioi.github.io/algorea-devdoc/api/#operation/itemActivityLogForItem) service,  include `answers` of types "`current`" and "`saved`" (with `activity_type` "current_answer" and "saved_answer").

**Comment by zenovich** [comment]
Should this change also affect itemActivityLogForAllItems? @smadbe

**Comment by smadbe** [comment]
> Should this change also affect itemActivityLogForAllItems? @smadbe

not necessarily but why not.. we will filter them out on the frontend if needed
