### ISSUE TITLE
Operation `groupUserProgress`: parameter `limit` has no effect

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaBackend#830]
[Link to the documentation](https://france-ioi.github.io/algorea-devdoc/api/#operation/groupUserProgress)

cURL request:

```sh
curl 'https://dev.algorea.org/api/groups/609422240375608067/user-progress?parent_item_ids=1352246428241737349&limit=25' \
  -H 'authorization: Bearer [usual user token]'
```

**Comment by smadbe** [comment]
I has an effect as the same command with limit=1 does not return the same response. What do you mean?

**Comment by ThomasJuster** [comment]
My bad, a misunderstanding on how to process this list
