### ISSUE TITLE
Change expected errors into sucesses: authentication service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#836]
## Overview

Modern browsers report any 4xx return code as an error logged in the console. These errors may be considered as issues by our customers and reported as such.  

So let's try to return non-error for error cases which are not considered by the frontend as errors (used on purpose to give a specific interpretation to errors)

### How it works now

Currently, when the frontend app starts, it does not (cannot) know if the browser has a cookie for the backend domain. If it has, nothing special needs to be done. If not, it needs to request the creation of an temp user.

So the "trick" the app currently does is to request a cookie refresh. If it works, it means it was ok (and we have the refresh cookie, which is not a bad thing). If it fails (we receive a 401), it means we need to ask for temp user creation. 

In practice, it means that everybody visiting the app for the first time gets a 401 (what we want to avoid).

(If the app is using tokens (stored in the browser storage) instead of cookies, the app knows whether there is a non-expired token so can skip this step)

### Proposal

In the *cookie + user was not authenticated* case, at the end, there a request for cookie based on the current one (returning the 401), followed by a request for a temp-user cookie. A way to prevent this first error is to merge these two requests (with the additional benefit to save a call, so additional delay at app startup).

Currently, the "Create or refresh an access token" service doc is:

> If the {code} is given and the "Authorization" header is not given, the service converts the given OAuth2 authorization code into tokens, creates or updates the authenticated user in the DB with the data returned by the login module, and saves new access & refresh tokens into the DB as well. If OAuth2 authentication has used the PKCE extension, the {code_verifier} should be provided so it can be sent together with the {code} to the authentication server.
> 
> If the {code} is not given while the "Authorization" header or/and the "access_token" is given (when both are given, the "Authorization" header is used and the cookie gets deleted), the service refreshes the access token (locally for temporary users or via the login module for normal users) and saves it into the DB keeping only the input token and the new token. Since the login module responds with both access and refresh tokens, the service updates the user's refresh token in this case as well. If there is no refresh token for the user in the DB, the 'not found' error is returned.
> 
> If attributes of the old and the new 'access_token' cookies are different (or the token is returned in the JSON), the old cookie gets deleted (otherwise, just overwritten).
> 
> * The "Authorization" header is not allowed when the {code} is given.
> *  When {use_cookie}=1, at least one of {cookie_secure} and {cookie_same_site} must be true.

Probably we have to add to the "If the {code} is not given while the "Authorization" header or/and the "access_token" is given" case, that it is for when the given authentication is valid. Then we can add a third case, when authentication is not given or invalid: create a temp user, behaving as the "Create a temporary user" works.

### Additional remarks

* `default_language` is needed for creating an temp user... this can be provided by the frontend in any call to "Create or refresh an access token" (maybe not in code/state case as it is useless anyway?).

* the frontend does not need to know if the token corresponds to a temp user creation or not (it fetches the user info anyway), so no need to add this info to the output

* unlike the "Create a temporary user" service, the "Create or refresh an access token" service does not clearly state what happens if a cookie is given together with a code/state. What should happen is probably that this cookie should be deleted (from the browser (if useful?) and from the db).   --> improve the doc (+ the tests if missing)

### Backward compatibility

With the two services merged, there is no need for the "Create a temporary user" service anymore as we were not allowed to call with authentication anyway. For backward compatibility though, we will remove it later.

## Acceptance criteria

- [x] merge "Create a temporary user" into "Create or refresh an access token" as describe
- [x] make sure the doc describes this third case
- [x] add to the doc what is described in the third "Additional remarks".
- [x] keep "Create a temporary user" as it is for now

**Comment by GeoffreyHuck** [comment]
Note considering the third remark, when a cookie is present and a `code` is sent. The behavior is already the one mentionned: deleting the cookie. The test is present here: https://github.com/France-ioi/AlgoreaBackend/blob/master/app/api/auth/create_access_token.feature#L514 `Scenario: Ignores and deletes the cookie when both code and access_token cookie are present`. So I'll just add the doc.
