### ISSUE TITLE
Forum: Thread listing service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#888]
## Overview 

Service to list the visible threads for a user.

On `GET /threads/`

## Input

Query args:
* `watched_group_id`
* `is_mine` (bool)
* `item_id` (optional)

Exactly one of [`watched_group_id`, `is_mine`] is given

## Output

* List of thread info with:
  - `item` : 
     - id
     - type
     - title
     - language_tag
  - `participant`
    - id 
    - login
    - first_name
    - last_name
  - `status`
  - `latest_update_at`
  - `message_count`

* If `is_mine = 1`, only threads whose the participant is the current-user and whose the item is visible (can_view >= content) by the current-user are returned
* If `is_mine = 0`, only [threads that the current-user can list](https://france-ioi.github.io/algorea-devdoc/forum/forum-perm/#listing--reading-a-thread) and whose the current-user is NOT the participant are returned
* If watched_group_id is given, only threads whose the participant is descendant (including self) of the `watched_group_id` are returned
* If `item_id` is given, only threads whose the `item_id` is or is descendant of the given `item_id` are returned
* `first_name` and `last_name` are only returned for the current user or if the user approved access to their personal info for some group managed by the current user

## Validations
* if `watched_group_id` given: the current-user must be (implicitly or explicitly) a manager with `can_watch_members` of `watched_group_id`
* if `item_id` is given, the current user needs `can_view >= content' on it

## Extra

* Use ordering and page limit as usual. By default, ordering should be `latest_update_at` desc (+ tie-breaking rules)
* The service should support filtering by `status` 
* The service should support filtering by `latest_update_gt` only return entries whose the `latest_update_at` is greater than a given datetime (given in UTC8601)

**Comment by GeoffreyHuck** [comment]
A question regarding: if

>  `item_id` is given, the current user needs `can_view >= content' on it

Is the can_view >= content only required for the `item_id`parameter, or for all the threads on children that can be returned ?

Also, when watched_group_id is used, we don't check can_view at all. Is it correct ?

**Comment by smadbe** [comment]
> > if `item_id` is given, the current user needs `can_view >= content' on it
> 
> Is the can_view >= content only required for the `item_id`parameter, or for all the threads on children that can be returned ?

Yes, for all.

> Also, when watched_group_id is used, we don't check can_view at all. Is it correct ?

No. We cannot visit an item cannot view all (nor we can see the title), so there is no point / no way of listing them.
