### ISSUE TITLE
Fix participant-progress service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#915]
## Motivations

The backend is supposed to return children of a chapter only if 2 conditions are met: the current user has `can_view>=content` on it and it has a (started) result.

The current participant-progress implementation does not implement the second rule as it return children even when the chapter has no result. 

## Subtasks
* do not return children in "participant-progress" when the current-user does not have started result on the item (including in observation mode)
* the "progress" over the item itself should still be returned (as long as it is visible to the current user)

**Comment by GeoffreyHuck** [comment]
A few questions:
- Is it a started `attempt` or a started `result` on the item that the current user needs to have?
- What is the observation mode and is it represented differently in the database?
- Do we check the `started` condition only for the given chapter `item_id`, or it can it also be on a parent?

**Comment by smadbe** [comment]
> Is it a started attempt or a started result on the item that the current user needs to have?

Result (fixed).


> What is the observation mode and is it represented differently in the database?

In the service, when `watched_group_id` is gien


> Do we check the started condition only for the given chapter item_id, or it can it also be on a parent?

In theory, it should have a started result path from a root... but in practice, we can check only the chapter result. (otherwise we make a lot this "expensive" check while it is not really a matter of "security" but more for data cleanness)
