### ISSUE TITLE
Some integrations tests are sometimes failing

### ISSUE THREAD

**Issue by GeoffreyHuck** [France-ioi/AlgoreaBackend#942]
It happened here:
https://app.circleci.com/pipelines/github/France-ioi/AlgoreaBackend/3306/workflows/5f030193-649e-433a-b32d-34040237a775/jobs/17300

Every once in a while, a few tests are failing, and re-running them make them pass.

**Comment by zenovich** [comment]
I believe it has been fixed by #1152. Anyway, as the link above displays an error, there's no way to see exactly what happened.
