### ISSUE TITLE
Add `can_request_help_to` in `getItem` 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#989]
## Request

Add info about the `can_request_help` perm  in the `itemView` service. Both in `permission` and `watched_group.permission`. 

## Motivation

The goal behind that request is, for the frontend, to know whether, on a task, to display button to display the forum (and to request forum information).  It can just be a single boolean, the detail of groups (not aggreggable) could be served by another service.

* So maybe that should only be given for the tasks. 

## Notes

* This should be aggregation on groups **and** items using the propagation condition on items_items (so using recursive queries?) 

* Don't forget to update the service description as `can_request_help_to`: `appears only in services that support this permission (see service description), and only if it is set`

# Initial request (outdated)
 
## Request

Add the `can_request_help_to` permission in the `itemView` service. Both in `permission` and `watched_group.permission`. 

## Motivation

The goal behind that request is, for the frontend, to know whether, on a task, to display button to display the forum (and to request forum information). Then once we open the forum pane, we need to know to what groups we can assign the request.

* So maybe that should only be given for the tasks. 

## Notes

* I assume that should be an array as they may be several groups

* This should be aggregation on groups **and** items using the propagation condition on items_items (so using recursive queries?) 

* As done at another place, if the group is "all users", it should be something like "{ all_group: true }" as the user does not what is the "all group" group. 

* If this makes this get-item request too expensive (called very often), we may reconsider including it in this request... or at least have `can_request_help: bool` in this request and the details in another request that we would call only when we need to know this list of groups (not that often actually)

* Don't forget to update the service description as `can_request_help_to`: `appears only in services that support this permission (see service description), and only if it is set`

**Comment by GeoffreyHuck** [comment]
Does the groups returned as `can_request_help_to` need to `be visible` by the current-user?

**Comment by smadbe** [comment]
The idea is to return a boolean for this service.
